namespace CarRental.Forms
{
    partial class frmKupacEdit
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            DevExpress.Utils.ContextButton contextButton1 = new DevExpress.Utils.ContextButton();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmKupacEdit));
            this.dataLayoutControl1 = new DevExpress.XtraDataLayout.DataLayoutControl();
            this.ratingControl1 = new DevExpress.XtraEditors.RatingControl();
            this.mainRibbonControl = new DevExpress.XtraBars.Ribbon.RibbonControl();
            this.bbiSave = new DevExpress.XtraBars.BarButtonItem();
            this.bbiSaveAndClose = new DevExpress.XtraBars.BarButtonItem();
            this.bbiSaveAndNew = new DevExpress.XtraBars.BarButtonItem();
            this.bbiReset = new DevExpress.XtraBars.BarButtonItem();
            this.bbiDelete = new DevExpress.XtraBars.BarButtonItem();
            this.bbiClose = new DevExpress.XtraBars.BarButtonItem();
            this.mainRibbonPage = new DevExpress.XtraBars.Ribbon.RibbonPage();
            this.mainRibbonPageGroup = new DevExpress.XtraBars.Ribbon.RibbonPageGroup();
            this.txtBrVozacka = new DevExpress.XtraEditors.TextEdit();
            this.txtBrPasos = new DevExpress.XtraEditors.TextEdit();
            this.txtBrLK = new DevExpress.XtraEditors.TextEdit();
            this.txtEmail = new DevExpress.XtraEditors.TextEdit();
            this.txtMobilni = new DevExpress.XtraEditors.TextEdit();
            this.txtTelefon = new DevExpress.XtraEditors.TextEdit();
            this.lkpMjestoStan = new DevExpress.XtraEditors.LookUpEdit();
            this.txtAdresa = new DevExpress.XtraEditors.TextEdit();
            this.dtRodj = new DevExpress.XtraEditors.DateEdit();
            this.cbPol = new DevExpress.XtraEditors.ComboBoxEdit();
            this.txtID = new DevExpress.XtraEditors.TextEdit();
            this.txtJMBG = new DevExpress.XtraEditors.TextEdit();
            this.xtraTabControl1 = new DevExpress.XtraTab.XtraTabControl();
            this.xtraTabPage1 = new DevExpress.XtraTab.XtraTabPage();
            this.gridControl1 = new DevExpress.XtraGrid.GridControl();
            this.gridView1 = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.memoNapomena = new DevExpress.XtraEditors.MemoEdit();
            this.pictureEdit1 = new DevExpress.XtraEditors.PictureEdit();
            this.txtPrezime = new DevExpress.XtraEditors.TextEdit();
            this.txtIme = new DevExpress.XtraEditors.TextEdit();
            this.layoutControlGroup1 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.autoGeneratedGroup0 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.autoGroupForRoot = new DevExpress.XtraLayout.LayoutControlGroup();
            this.autoGroupForPhoto = new DevExpress.XtraLayout.LayoutControlGroup();
            this.layoutControlItem1 = new DevExpress.XtraLayout.LayoutControlItem();
            this.autoGroupForFirstAndLastName = new DevExpress.XtraLayout.LayoutControlGroup();
            this.autoGroupForTabs = new DevExpress.XtraLayout.TabbedControlGroup();
            this.autoGroupForContact = new DevExpress.XtraLayout.LayoutControlGroup();
            this.autoGroupForBDateAndGender = new DevExpress.XtraLayout.LayoutControlGroup();
            this.layoutControlGroup5 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.layoutControlItem8 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem13 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem12 = new DevExpress.XtraLayout.LayoutControlItem();
            this.autoGroupForHomeAddressAndPhone = new DevExpress.XtraLayout.LayoutControlGroup();
            this.layoutControlGroup4 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.layoutControlItem18 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem19 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem22 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem17 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem20 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlGroup3 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.layoutControlItem5 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem6 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem10 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlGroup2 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.layoutControlItem4 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem2 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem3 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem9 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem11 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem7 = new DevExpress.XtraLayout.LayoutControlItem();
            this.gridColumn1 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn2 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn3 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn4 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn5 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn6 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn7 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn8 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn9 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn10 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn12 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn11 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn13 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn14 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn15 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn16 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn17 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn18 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn19 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn20 = new DevExpress.XtraGrid.Columns.GridColumn();
            ((System.ComponentModel.ISupportInitialize)(this.dataLayoutControl1)).BeginInit();
            this.dataLayoutControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ratingControl1.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.mainRibbonControl)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtBrVozacka.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtBrPasos.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtBrLK.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtEmail.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtMobilni.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtTelefon.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lkpMjestoStan.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtAdresa.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dtRodj.Properties.CalendarTimeProperties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dtRodj.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cbPol.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtID.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtJMBG.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.xtraTabControl1)).BeginInit();
            this.xtraTabControl1.SuspendLayout();
            this.xtraTabPage1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gridControl1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.memoNapomena.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureEdit1.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtPrezime.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtIme.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGeneratedGroup0)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForRoot)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForPhoto)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForFirstAndLastName)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForTabs)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForContact)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForBDateAndGender)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem13)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem12)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForHomeAddressAndPhone)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem18)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem19)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem22)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem17)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem20)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem10)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem9)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem11)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem7)).BeginInit();
            this.SuspendLayout();
            // 
            // dataLayoutControl1
            // 
            this.dataLayoutControl1.AllowCustomization = false;
            this.dataLayoutControl1.Controls.Add(this.ratingControl1);
            this.dataLayoutControl1.Controls.Add(this.txtBrVozacka);
            this.dataLayoutControl1.Controls.Add(this.txtBrPasos);
            this.dataLayoutControl1.Controls.Add(this.txtBrLK);
            this.dataLayoutControl1.Controls.Add(this.txtEmail);
            this.dataLayoutControl1.Controls.Add(this.txtMobilni);
            this.dataLayoutControl1.Controls.Add(this.txtTelefon);
            this.dataLayoutControl1.Controls.Add(this.lkpMjestoStan);
            this.dataLayoutControl1.Controls.Add(this.txtAdresa);
            this.dataLayoutControl1.Controls.Add(this.dtRodj);
            this.dataLayoutControl1.Controls.Add(this.cbPol);
            this.dataLayoutControl1.Controls.Add(this.txtID);
            this.dataLayoutControl1.Controls.Add(this.txtJMBG);
            this.dataLayoutControl1.Controls.Add(this.xtraTabControl1);
            this.dataLayoutControl1.Controls.Add(this.memoNapomena);
            this.dataLayoutControl1.Controls.Add(this.pictureEdit1);
            this.dataLayoutControl1.Controls.Add(this.txtPrezime);
            this.dataLayoutControl1.Controls.Add(this.txtIme);
            this.dataLayoutControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dataLayoutControl1.Location = new System.Drawing.Point(0, 116);
            this.dataLayoutControl1.Name = "dataLayoutControl1";
            this.dataLayoutControl1.OptionsCustomizationForm.DesignTimeCustomizationFormPositionAndSize = new System.Drawing.Rectangle(787, 321, 450, 400);
            this.dataLayoutControl1.Root = this.layoutControlGroup1;
            this.dataLayoutControl1.Size = new System.Drawing.Size(1133, 663);
            this.dataLayoutControl1.TabIndex = 0;
            // 
            // ratingControl1
            // 
            this.ratingControl1.EditValue = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.ratingControl1.Enabled = false;
            this.ratingControl1.Location = new System.Drawing.Point(982, 12);
            this.ratingControl1.MenuManager = this.mainRibbonControl;
            this.ratingControl1.Name = "ratingControl1";
            this.ratingControl1.Properties.FillPrecision = DevExpress.XtraEditors.RatingItemFillPrecision.Exact;
            this.ratingControl1.Rating = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.ratingControl1.Size = new System.Drawing.Size(87, 16);
            this.ratingControl1.StyleController = this.dataLayoutControl1;
            this.ratingControl1.TabIndex = 16;
            this.ratingControl1.Text = "ratingControl1";
            // 
            // mainRibbonControl
            // 
            this.mainRibbonControl.ExpandCollapseItem.Id = 0;
            this.mainRibbonControl.Items.AddRange(new DevExpress.XtraBars.BarItem[] {
            this.mainRibbonControl.ExpandCollapseItem,
            this.bbiSave,
            this.bbiSaveAndClose,
            this.bbiSaveAndNew,
            this.bbiReset,
            this.bbiDelete,
            this.bbiClose});
            this.mainRibbonControl.Location = new System.Drawing.Point(0, 0);
            this.mainRibbonControl.MaxItemId = 10;
            this.mainRibbonControl.MdiMergeStyle = DevExpress.XtraBars.Ribbon.RibbonMdiMergeStyle.Always;
            this.mainRibbonControl.Name = "mainRibbonControl";
            this.mainRibbonControl.Pages.AddRange(new DevExpress.XtraBars.Ribbon.RibbonPage[] {
            this.mainRibbonPage});
            this.mainRibbonControl.RibbonStyle = DevExpress.XtraBars.Ribbon.RibbonControlStyle.Office2013;
            this.mainRibbonControl.ShowApplicationButton = DevExpress.Utils.DefaultBoolean.False;
            this.mainRibbonControl.Size = new System.Drawing.Size(1133, 116);
            this.mainRibbonControl.ToolbarLocation = DevExpress.XtraBars.Ribbon.RibbonQuickAccessToolbarLocation.Hidden;
            // 
            // bbiSave
            // 
            this.bbiSave.Caption = "Snimi";
            this.bbiSave.Id = 2;
            this.bbiSave.ImageOptions.ImageUri.Uri = "Save";
            this.bbiSave.Name = "bbiSave";
            this.bbiSave.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.bbiSave_ItemClick);
            // 
            // bbiSaveAndClose
            // 
            this.bbiSaveAndClose.Caption = "Snimi i zatvori";
            this.bbiSaveAndClose.Id = 3;
            this.bbiSaveAndClose.ImageOptions.ImageUri.Uri = "SaveAndClose";
            this.bbiSaveAndClose.Name = "bbiSaveAndClose";
            this.bbiSaveAndClose.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.bbiSaveAndClose_ItemClick);
            // 
            // bbiSaveAndNew
            // 
            this.bbiSaveAndNew.Caption = "Snimi i novi";
            this.bbiSaveAndNew.Id = 4;
            this.bbiSaveAndNew.ImageOptions.ImageUri.Uri = "SaveAndNew";
            this.bbiSaveAndNew.Name = "bbiSaveAndNew";
            this.bbiSaveAndNew.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.bbiSaveAndNew_ItemClick);
            // 
            // bbiReset
            // 
            this.bbiReset.Caption = "Poništi izmjene";
            this.bbiReset.Id = 5;
            this.bbiReset.ImageOptions.ImageUri.Uri = "Reset";
            this.bbiReset.Name = "bbiReset";
            this.bbiReset.Visibility = DevExpress.XtraBars.BarItemVisibility.Never;
            // 
            // bbiDelete
            // 
            this.bbiDelete.Caption = "Ukloni sliku";
            this.bbiDelete.Id = 6;
            this.bbiDelete.ImageOptions.ImageUri.Uri = "Delete";
            this.bbiDelete.Name = "bbiDelete";
            this.bbiDelete.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.bbiDelete_ItemClick);
            // 
            // bbiClose
            // 
            this.bbiClose.Caption = "Zatvori";
            this.bbiClose.Id = 7;
            this.bbiClose.ImageOptions.ImageUri.Uri = "Close";
            this.bbiClose.Name = "bbiClose";
            this.bbiClose.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.bbiClose_ItemClick);
            // 
            // mainRibbonPage
            // 
            this.mainRibbonPage.Groups.AddRange(new DevExpress.XtraBars.Ribbon.RibbonPageGroup[] {
            this.mainRibbonPageGroup});
            this.mainRibbonPage.MergeOrder = 0;
            this.mainRibbonPage.Name = "mainRibbonPage";
            this.mainRibbonPage.Text = "Korisnik usluge";
            // 
            // mainRibbonPageGroup
            // 
            this.mainRibbonPageGroup.AllowTextClipping = false;
            this.mainRibbonPageGroup.ItemLinks.Add(this.bbiSave);
            this.mainRibbonPageGroup.ItemLinks.Add(this.bbiSaveAndClose);
            this.mainRibbonPageGroup.ItemLinks.Add(this.bbiSaveAndNew);
            this.mainRibbonPageGroup.ItemLinks.Add(this.bbiReset);
            this.mainRibbonPageGroup.ItemLinks.Add(this.bbiDelete);
            this.mainRibbonPageGroup.ItemLinks.Add(this.bbiClose);
            this.mainRibbonPageGroup.Name = "mainRibbonPageGroup";
            this.mainRibbonPageGroup.ShowCaptionButton = false;
            this.mainRibbonPageGroup.Text = "Podaci";
            // 
            // txtBrVozacka
            // 
            this.txtBrVozacka.Location = new System.Drawing.Point(415, 377);
            this.txtBrVozacka.MenuManager = this.mainRibbonControl;
            this.txtBrVozacka.Name = "txtBrVozacka";
            this.txtBrVozacka.Size = new System.Drawing.Size(682, 20);
            this.txtBrVozacka.StyleController = this.dataLayoutControl1;
            this.txtBrVozacka.TabIndex = 14;
            // 
            // txtBrPasos
            // 
            this.txtBrPasos.Location = new System.Drawing.Point(415, 353);
            this.txtBrPasos.MenuManager = this.mainRibbonControl;
            this.txtBrPasos.Name = "txtBrPasos";
            this.txtBrPasos.Size = new System.Drawing.Size(682, 20);
            this.txtBrPasos.StyleController = this.dataLayoutControl1;
            this.txtBrPasos.TabIndex = 13;
            // 
            // txtBrLK
            // 
            this.txtBrLK.Location = new System.Drawing.Point(415, 329);
            this.txtBrLK.MenuManager = this.mainRibbonControl;
            this.txtBrLK.Name = "txtBrLK";
            this.txtBrLK.Size = new System.Drawing.Size(682, 20);
            this.txtBrLK.StyleController = this.dataLayoutControl1;
            this.txtBrLK.TabIndex = 12;
            // 
            // txtEmail
            // 
            this.txtEmail.Location = new System.Drawing.Point(415, 282);
            this.txtEmail.Name = "txtEmail";
            this.txtEmail.Size = new System.Drawing.Size(682, 20);
            this.txtEmail.StyleController = this.dataLayoutControl1;
            this.txtEmail.TabIndex = 11;
            // 
            // txtMobilni
            // 
            this.txtMobilni.Location = new System.Drawing.Point(415, 258);
            this.txtMobilni.Name = "txtMobilni";
            this.txtMobilni.Size = new System.Drawing.Size(682, 20);
            this.txtMobilni.StyleController = this.dataLayoutControl1;
            this.txtMobilni.TabIndex = 10;
            // 
            // txtTelefon
            // 
            this.txtTelefon.Location = new System.Drawing.Point(415, 234);
            this.txtTelefon.Name = "txtTelefon";
            this.txtTelefon.Size = new System.Drawing.Size(682, 20);
            this.txtTelefon.StyleController = this.dataLayoutControl1;
            this.txtTelefon.TabIndex = 9;
            // 
            // lkpMjestoStan
            // 
            this.lkpMjestoStan.Location = new System.Drawing.Point(415, 186);
            this.lkpMjestoStan.Name = "lkpMjestoStan";
            this.lkpMjestoStan.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.lkpMjestoStan.Properties.DisplayMember = "Naziv";
            this.lkpMjestoStan.Properties.NullText = "Izaberite...";
            this.lkpMjestoStan.Properties.ValueMember = "ID";
            this.lkpMjestoStan.Size = new System.Drawing.Size(682, 20);
            this.lkpMjestoStan.StyleController = this.dataLayoutControl1;
            this.lkpMjestoStan.TabIndex = 7;
            // 
            // txtAdresa
            // 
            this.txtAdresa.Location = new System.Drawing.Point(415, 210);
            this.txtAdresa.Name = "txtAdresa";
            this.txtAdresa.Size = new System.Drawing.Size(682, 20);
            this.txtAdresa.StyleController = this.dataLayoutControl1;
            this.txtAdresa.TabIndex = 8;
            // 
            // dtRodj
            // 
            this.dtRodj.EditValue = null;
            this.dtRodj.Location = new System.Drawing.Point(415, 115);
            this.dtRodj.Name = "dtRodj";
            this.dtRodj.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.dtRodj.Properties.CalendarTimeProperties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.dtRodj.Size = new System.Drawing.Size(682, 20);
            this.dtRodj.StyleController = this.dataLayoutControl1;
            this.dtRodj.TabIndex = 6;
            // 
            // cbPol
            // 
            this.cbPol.Location = new System.Drawing.Point(415, 139);
            this.cbPol.Name = "cbPol";
            this.cbPol.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.cbPol.Properties.Items.AddRange(new object[] {
            "Muški",
            "Ženski"});
            this.cbPol.Size = new System.Drawing.Size(682, 20);
            this.cbPol.StyleController = this.dataLayoutControl1;
            this.cbPol.TabIndex = 5;
            // 
            // txtID
            // 
            this.txtID.Location = new System.Drawing.Point(372, 12);
            this.txtID.Name = "txtID";
            this.txtID.Properties.Appearance.Font = new System.Drawing.Font("Tahoma", 14F);
            this.txtID.Properties.Appearance.Options.UseFont = true;
            this.txtID.Properties.ReadOnly = true;
            this.txtID.Size = new System.Drawing.Size(50, 30);
            this.txtID.StyleController = this.dataLayoutControl1;
            this.txtID.TabIndex = 3;
            // 
            // txtJMBG
            // 
            this.txtJMBG.Location = new System.Drawing.Point(415, 91);
            this.txtJMBG.Name = "txtJMBG";
            this.txtJMBG.Properties.MaxLength = 13;
            this.txtJMBG.Size = new System.Drawing.Size(682, 20);
            this.txtJMBG.StyleController = this.dataLayoutControl1;
            this.txtJMBG.TabIndex = 4;
            // 
            // xtraTabControl1
            // 
            this.xtraTabControl1.Location = new System.Drawing.Point(12, 425);
            this.xtraTabControl1.Name = "xtraTabControl1";
            this.xtraTabControl1.SelectedTabPage = this.xtraTabPage1;
            this.xtraTabControl1.Size = new System.Drawing.Size(1109, 226);
            this.xtraTabControl1.TabIndex = 15;
            this.xtraTabControl1.TabPages.AddRange(new DevExpress.XtraTab.XtraTabPage[] {
            this.xtraTabPage1});
            // 
            // xtraTabPage1
            // 
            this.xtraTabPage1.Controls.Add(this.gridControl1);
            this.xtraTabPage1.Name = "xtraTabPage1";
            this.xtraTabPage1.Size = new System.Drawing.Size(1103, 198);
            this.xtraTabPage1.Text = "Kartica";
            // 
            // gridControl1
            // 
            this.gridControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridControl1.Location = new System.Drawing.Point(0, 0);
            this.gridControl1.MainView = this.gridView1;
            this.gridControl1.MenuManager = this.mainRibbonControl;
            this.gridControl1.Name = "gridControl1";
            this.gridControl1.Size = new System.Drawing.Size(1103, 198);
            this.gridControl1.TabIndex = 1;
            this.gridControl1.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] {
            this.gridView1});
            // 
            // gridView1
            // 
            this.gridView1.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] {
            this.gridColumn1,
            this.gridColumn2,
            this.gridColumn3,
            this.gridColumn4,
            this.gridColumn5,
            this.gridColumn6,
            this.gridColumn7,
            this.gridColumn8,
            this.gridColumn9,
            this.gridColumn10,
            this.gridColumn20,
            this.gridColumn12,
            this.gridColumn11,
            this.gridColumn13,
            this.gridColumn14,
            this.gridColumn15,
            this.gridColumn16,
            this.gridColumn17,
            this.gridColumn18,
            this.gridColumn19});
            this.gridView1.GridControl = this.gridControl1;
            this.gridView1.Name = "gridView1";
            this.gridView1.OptionsBehavior.Editable = false;
            this.gridView1.OptionsView.ShowGroupPanel = false;
            // 
            // memoNapomena
            // 
            this.memoNapomena.Location = new System.Drawing.Point(302, 80);
            this.memoNapomena.Name = "memoNapomena";
            this.memoNapomena.Size = new System.Drawing.Size(807, 329);
            this.memoNapomena.StyleController = this.dataLayoutControl1;
            this.memoNapomena.TabIndex = 7;
            // 
            // pictureEdit1
            // 
            this.pictureEdit1.Cursor = System.Windows.Forms.Cursors.Default;
            this.pictureEdit1.Location = new System.Drawing.Point(12, 12);
            this.pictureEdit1.Name = "pictureEdit1";
            contextButton1.Alignment = DevExpress.Utils.ContextItemAlignment.BottomFar;
            contextButton1.Caption = "Dodaj/promjeni fotografiju";
            contextButton1.Id = new System.Guid("8877d5fc-004a-4264-9174-58d9edcc153b");
            contextButton1.Name = "btnUcitajSliku";
            contextButton1.ToolTip = "Učitaj sliku";
            this.pictureEdit1.Properties.ContextButtons.Add(contextButton1);
            this.pictureEdit1.Properties.InitialImage = ((System.Drawing.Image)(resources.GetObject("pictureEdit1.Properties.InitialImage")));
            this.pictureEdit1.Properties.ShowCameraMenuItem = DevExpress.XtraEditors.Controls.CameraMenuItemVisibility.Auto;
            this.pictureEdit1.Properties.SizeMode = DevExpress.XtraEditors.Controls.PictureSizeMode.Squeeze;
            this.pictureEdit1.Properties.ZoomAccelerationFactor = 1D;
            this.pictureEdit1.Size = new System.Drawing.Size(274, 409);
            this.pictureEdit1.StyleController = this.dataLayoutControl1;
            this.pictureEdit1.TabIndex = 0;
            this.pictureEdit1.ContextButtonClick += new DevExpress.Utils.ContextItemClickEventHandler(this.pictureEdit1_ContextButtonClick);
            // 
            // txtPrezime
            // 
            this.txtPrezime.EditValue = "";
            this.txtPrezime.Location = new System.Drawing.Point(468, 12);
            this.txtPrezime.Name = "txtPrezime";
            this.txtPrezime.Properties.Appearance.Font = new System.Drawing.Font("Tahoma", 14F, System.Drawing.FontStyle.Bold);
            this.txtPrezime.Properties.Appearance.Options.UseFont = true;
            this.txtPrezime.Size = new System.Drawing.Size(204, 30);
            this.txtPrezime.StyleController = this.dataLayoutControl1;
            this.txtPrezime.TabIndex = 1;
            // 
            // txtIme
            // 
            this.txtIme.Location = new System.Drawing.Point(699, 12);
            this.txtIme.Name = "txtIme";
            this.txtIme.Properties.Appearance.Font = new System.Drawing.Font("Tahoma", 14F, System.Drawing.FontStyle.Bold);
            this.txtIme.Properties.Appearance.Options.UseFont = true;
            this.txtIme.Size = new System.Drawing.Size(197, 30);
            this.txtIme.StyleController = this.dataLayoutControl1;
            this.txtIme.TabIndex = 2;
            // 
            // layoutControlGroup1
            // 
            this.layoutControlGroup1.CustomizationFormText = "Root";
            this.layoutControlGroup1.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            this.layoutControlGroup1.GroupBordersVisible = false;
            this.layoutControlGroup1.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.autoGeneratedGroup0});
            this.layoutControlGroup1.Location = new System.Drawing.Point(0, 0);
            this.layoutControlGroup1.Name = "Root";
            this.layoutControlGroup1.Size = new System.Drawing.Size(1133, 663);
            this.layoutControlGroup1.TextVisible = false;
            // 
            // autoGeneratedGroup0
            // 
            this.autoGeneratedGroup0.AllowDrawBackground = false;
            this.autoGeneratedGroup0.CustomizationFormText = "autoGeneratedGroup0";
            this.autoGeneratedGroup0.GroupBordersVisible = false;
            this.autoGeneratedGroup0.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.autoGroupForRoot});
            this.autoGeneratedGroup0.Location = new System.Drawing.Point(0, 0);
            this.autoGeneratedGroup0.Name = "autoGeneratedGroup0";
            this.autoGeneratedGroup0.Size = new System.Drawing.Size(1113, 643);
            // 
            // autoGroupForRoot
            // 
            this.autoGroupForRoot.CustomizationFormText = "Root";
            this.autoGroupForRoot.GroupBordersVisible = false;
            this.autoGroupForRoot.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.autoGroupForPhoto});
            this.autoGroupForRoot.Location = new System.Drawing.Point(0, 0);
            this.autoGroupForRoot.Name = "autoGroupForRoot";
            this.autoGroupForRoot.Size = new System.Drawing.Size(1113, 643);
            this.autoGroupForRoot.Text = "Root";
            // 
            // autoGroupForPhoto
            // 
            this.autoGroupForPhoto.CustomizationFormText = "Photo";
            this.autoGroupForPhoto.DefaultLayoutType = DevExpress.XtraLayout.Utils.LayoutType.Horizontal;
            this.autoGroupForPhoto.GroupBordersVisible = false;
            this.autoGroupForPhoto.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.layoutControlItem1,
            this.autoGroupForFirstAndLastName,
            this.layoutControlItem7});
            this.autoGroupForPhoto.Location = new System.Drawing.Point(0, 0);
            this.autoGroupForPhoto.Name = "autoGroupForPhoto";
            this.autoGroupForPhoto.Size = new System.Drawing.Size(1113, 643);
            this.autoGroupForPhoto.Text = "Photo";
            // 
            // layoutControlItem1
            // 
            this.layoutControlItem1.Control = this.pictureEdit1;
            this.layoutControlItem1.Location = new System.Drawing.Point(0, 0);
            this.layoutControlItem1.Name = "layoutControlItem1";
            this.layoutControlItem1.Size = new System.Drawing.Size(278, 413);
            this.layoutControlItem1.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem1.TextVisible = false;
            // 
            // autoGroupForFirstAndLastName
            // 
            this.autoGroupForFirstAndLastName.CustomizationFormText = "FirstAndLastName";
            this.autoGroupForFirstAndLastName.GroupBordersVisible = false;
            this.autoGroupForFirstAndLastName.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.autoGroupForTabs,
            this.layoutControlItem2,
            this.layoutControlItem3,
            this.layoutControlItem9,
            this.layoutControlItem11});
            this.autoGroupForFirstAndLastName.Location = new System.Drawing.Point(278, 0);
            this.autoGroupForFirstAndLastName.Name = "autoGroupForFirstAndLastName";
            this.autoGroupForFirstAndLastName.Size = new System.Drawing.Size(835, 413);
            this.autoGroupForFirstAndLastName.Text = "FirstAndLastName";
            // 
            // autoGroupForTabs
            // 
            this.autoGroupForTabs.CustomizationFormText = "Tabs";
            this.autoGroupForTabs.Location = new System.Drawing.Point(0, 34);
            this.autoGroupForTabs.Name = "autoGroupForTabs";
            this.autoGroupForTabs.SelectedTabPage = this.autoGroupForContact;
            this.autoGroupForTabs.SelectedTabPageIndex = 0;
            this.autoGroupForTabs.Size = new System.Drawing.Size(835, 379);
            this.autoGroupForTabs.TabPages.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.autoGroupForContact,
            this.layoutControlGroup2});
            this.autoGroupForTabs.Text = "Tabs";
            // 
            // autoGroupForContact
            // 
            this.autoGroupForContact.CustomizationFormText = "Kontakt";
            this.autoGroupForContact.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.autoGroupForBDateAndGender,
            this.autoGroupForHomeAddressAndPhone});
            this.autoGroupForContact.Location = new System.Drawing.Point(0, 0);
            this.autoGroupForContact.Name = "autoGroupForContact";
            this.autoGroupForContact.Size = new System.Drawing.Size(811, 333);
            this.autoGroupForContact.Text = "Kontakt";
            // 
            // autoGroupForBDateAndGender
            // 
            this.autoGroupForBDateAndGender.CustomizationFormText = "BDateAndGender";
            this.autoGroupForBDateAndGender.DefaultLayoutType = DevExpress.XtraLayout.Utils.LayoutType.Horizontal;
            this.autoGroupForBDateAndGender.GroupBordersVisible = false;
            this.autoGroupForBDateAndGender.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.layoutControlGroup5});
            this.autoGroupForBDateAndGender.Location = new System.Drawing.Point(0, 0);
            this.autoGroupForBDateAndGender.Name = "autoGroupForBDateAndGender";
            this.autoGroupForBDateAndGender.Size = new System.Drawing.Size(811, 95);
            this.autoGroupForBDateAndGender.Text = "BDateAndGender";
            // 
            // layoutControlGroup5
            // 
            this.layoutControlGroup5.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.layoutControlItem8,
            this.layoutControlItem13,
            this.layoutControlItem12});
            this.layoutControlGroup5.Location = new System.Drawing.Point(0, 0);
            this.layoutControlGroup5.Name = "layoutControlGroup5";
            this.layoutControlGroup5.Size = new System.Drawing.Size(811, 95);
            this.layoutControlGroup5.Text = "Opšti podaci";
            this.layoutControlGroup5.TextLocation = DevExpress.Utils.Locations.Left;
            // 
            // layoutControlItem8
            // 
            this.layoutControlItem8.Control = this.txtJMBG;
            this.layoutControlItem8.Location = new System.Drawing.Point(0, 0);
            this.layoutControlItem8.Name = "layoutControlItem8";
            this.layoutControlItem8.Size = new System.Drawing.Size(768, 24);
            this.layoutControlItem8.Text = "JMBG";
            this.layoutControlItem8.TextSize = new System.Drawing.Size(79, 13);
            // 
            // layoutControlItem13
            // 
            this.layoutControlItem13.Control = this.dtRodj;
            this.layoutControlItem13.Location = new System.Drawing.Point(0, 24);
            this.layoutControlItem13.Name = "layoutControlItem13";
            this.layoutControlItem13.Size = new System.Drawing.Size(768, 24);
            this.layoutControlItem13.Text = "Datum rođenja";
            this.layoutControlItem13.TextSize = new System.Drawing.Size(79, 13);
            // 
            // layoutControlItem12
            // 
            this.layoutControlItem12.Control = this.cbPol;
            this.layoutControlItem12.Location = new System.Drawing.Point(0, 48);
            this.layoutControlItem12.Name = "layoutControlItem12";
            this.layoutControlItem12.Size = new System.Drawing.Size(768, 24);
            this.layoutControlItem12.Text = "Pol";
            this.layoutControlItem12.TextSize = new System.Drawing.Size(79, 13);
            // 
            // autoGroupForHomeAddressAndPhone
            // 
            this.autoGroupForHomeAddressAndPhone.CustomizationFormText = "HomeAddressAndPhone";
            this.autoGroupForHomeAddressAndPhone.DefaultLayoutType = DevExpress.XtraLayout.Utils.LayoutType.Horizontal;
            this.autoGroupForHomeAddressAndPhone.GroupBordersVisible = false;
            this.autoGroupForHomeAddressAndPhone.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.layoutControlGroup4,
            this.layoutControlGroup3});
            this.autoGroupForHomeAddressAndPhone.Location = new System.Drawing.Point(0, 95);
            this.autoGroupForHomeAddressAndPhone.Name = "autoGroupForHomeAddressAndPhone";
            this.autoGroupForHomeAddressAndPhone.Size = new System.Drawing.Size(811, 238);
            this.autoGroupForHomeAddressAndPhone.Text = "HomeAddressAndPhone";
            // 
            // layoutControlGroup4
            // 
            this.layoutControlGroup4.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.layoutControlItem18,
            this.layoutControlItem19,
            this.layoutControlItem22,
            this.layoutControlItem17,
            this.layoutControlItem20});
            this.layoutControlGroup4.Location = new System.Drawing.Point(0, 0);
            this.layoutControlGroup4.Name = "layoutControlGroup4";
            this.layoutControlGroup4.Size = new System.Drawing.Size(811, 143);
            this.layoutControlGroup4.Text = "Kontakt";
            this.layoutControlGroup4.TextLocation = DevExpress.Utils.Locations.Left;
            // 
            // layoutControlItem18
            // 
            this.layoutControlItem18.Control = this.lkpMjestoStan;
            this.layoutControlItem18.Location = new System.Drawing.Point(0, 0);
            this.layoutControlItem18.Name = "layoutControlItem18";
            this.layoutControlItem18.Size = new System.Drawing.Size(768, 24);
            this.layoutControlItem18.Text = "Mjesto";
            this.layoutControlItem18.TextSize = new System.Drawing.Size(79, 13);
            // 
            // layoutControlItem19
            // 
            this.layoutControlItem19.Control = this.txtTelefon;
            this.layoutControlItem19.Location = new System.Drawing.Point(0, 48);
            this.layoutControlItem19.Name = "layoutControlItem19";
            this.layoutControlItem19.Size = new System.Drawing.Size(768, 24);
            this.layoutControlItem19.Text = "Telefon";
            this.layoutControlItem19.TextSize = new System.Drawing.Size(79, 13);
            // 
            // layoutControlItem22
            // 
            this.layoutControlItem22.Control = this.txtEmail;
            this.layoutControlItem22.Location = new System.Drawing.Point(0, 96);
            this.layoutControlItem22.Name = "layoutControlItem22";
            this.layoutControlItem22.Size = new System.Drawing.Size(768, 24);
            this.layoutControlItem22.Text = "e-mail";
            this.layoutControlItem22.TextSize = new System.Drawing.Size(79, 13);
            // 
            // layoutControlItem17
            // 
            this.layoutControlItem17.Control = this.txtAdresa;
            this.layoutControlItem17.Location = new System.Drawing.Point(0, 24);
            this.layoutControlItem17.Name = "layoutControlItem17";
            this.layoutControlItem17.Size = new System.Drawing.Size(768, 24);
            this.layoutControlItem17.Text = "Adresa";
            this.layoutControlItem17.TextSize = new System.Drawing.Size(79, 13);
            // 
            // layoutControlItem20
            // 
            this.layoutControlItem20.Control = this.txtMobilni;
            this.layoutControlItem20.Location = new System.Drawing.Point(0, 72);
            this.layoutControlItem20.Name = "layoutControlItem20";
            this.layoutControlItem20.Size = new System.Drawing.Size(768, 24);
            this.layoutControlItem20.Text = "Mobilni";
            this.layoutControlItem20.TextSize = new System.Drawing.Size(79, 13);
            // 
            // layoutControlGroup3
            // 
            this.layoutControlGroup3.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.layoutControlItem5,
            this.layoutControlItem6,
            this.layoutControlItem10});
            this.layoutControlGroup3.Location = new System.Drawing.Point(0, 143);
            this.layoutControlGroup3.Name = "layoutControlGroup3";
            this.layoutControlGroup3.Size = new System.Drawing.Size(811, 95);
            this.layoutControlGroup3.Text = "Dokumenti";
            this.layoutControlGroup3.TextLocation = DevExpress.Utils.Locations.Left;
            // 
            // layoutControlItem5
            // 
            this.layoutControlItem5.Control = this.txtBrLK;
            this.layoutControlItem5.Location = new System.Drawing.Point(0, 0);
            this.layoutControlItem5.Name = "layoutControlItem5";
            this.layoutControlItem5.Size = new System.Drawing.Size(768, 24);
            this.layoutControlItem5.Text = "Lična karta";
            this.layoutControlItem5.TextSize = new System.Drawing.Size(79, 13);
            // 
            // layoutControlItem6
            // 
            this.layoutControlItem6.Control = this.txtBrPasos;
            this.layoutControlItem6.Location = new System.Drawing.Point(0, 24);
            this.layoutControlItem6.Name = "layoutControlItem6";
            this.layoutControlItem6.Size = new System.Drawing.Size(768, 24);
            this.layoutControlItem6.Text = "Pasoš";
            this.layoutControlItem6.TextSize = new System.Drawing.Size(79, 13);
            // 
            // layoutControlItem10
            // 
            this.layoutControlItem10.Control = this.txtBrVozacka;
            this.layoutControlItem10.Location = new System.Drawing.Point(0, 48);
            this.layoutControlItem10.Name = "layoutControlItem10";
            this.layoutControlItem10.Size = new System.Drawing.Size(768, 24);
            this.layoutControlItem10.Text = "Vozačka dozvola";
            this.layoutControlItem10.TextSize = new System.Drawing.Size(79, 13);
            // 
            // layoutControlGroup2
            // 
            this.layoutControlGroup2.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.layoutControlItem4});
            this.layoutControlGroup2.Location = new System.Drawing.Point(0, 0);
            this.layoutControlGroup2.Name = "layoutControlGroup2";
            this.layoutControlGroup2.Size = new System.Drawing.Size(811, 333);
            this.layoutControlGroup2.Text = "Napomena";
            // 
            // layoutControlItem4
            // 
            this.layoutControlItem4.Control = this.memoNapomena;
            this.layoutControlItem4.Location = new System.Drawing.Point(0, 0);
            this.layoutControlItem4.Name = "layoutControlItem4";
            this.layoutControlItem4.Size = new System.Drawing.Size(811, 333);
            this.layoutControlItem4.Text = "Napomena";
            this.layoutControlItem4.TextLocation = DevExpress.Utils.Locations.Top;
            this.layoutControlItem4.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem4.TextVisible = false;
            // 
            // layoutControlItem2
            // 
            this.layoutControlItem2.Control = this.txtPrezime;
            this.layoutControlItem2.Location = new System.Drawing.Point(136, 0);
            this.layoutControlItem2.Name = "layoutControlItem2";
            this.layoutControlItem2.Size = new System.Drawing.Size(250, 34);
            this.layoutControlItem2.Text = "Prezime";
            this.layoutControlItem2.TextAlignMode = DevExpress.XtraLayout.TextAlignModeItem.AutoSize;
            this.layoutControlItem2.TextSize = new System.Drawing.Size(37, 13);
            this.layoutControlItem2.TextToControlDistance = 5;
            // 
            // layoutControlItem3
            // 
            this.layoutControlItem3.Control = this.txtIme;
            this.layoutControlItem3.Location = new System.Drawing.Point(386, 0);
            this.layoutControlItem3.Name = "layoutControlItem3";
            this.layoutControlItem3.Size = new System.Drawing.Size(224, 34);
            this.layoutControlItem3.Text = "Ime";
            this.layoutControlItem3.TextAlignMode = DevExpress.XtraLayout.TextAlignModeItem.AutoSize;
            this.layoutControlItem3.TextSize = new System.Drawing.Size(18, 13);
            this.layoutControlItem3.TextToControlDistance = 5;
            // 
            // layoutControlItem9
            // 
            this.layoutControlItem9.AppearanceItemCaption.Font = new System.Drawing.Font("Tahoma", 10F);
            this.layoutControlItem9.AppearanceItemCaption.Options.UseFont = true;
            this.layoutControlItem9.Control = this.txtID;
            this.layoutControlItem9.Location = new System.Drawing.Point(0, 0);
            this.layoutControlItem9.Name = "layoutControlItem9";
            this.layoutControlItem9.Size = new System.Drawing.Size(136, 34);
            this.layoutControlItem9.Text = "Šifra";
            this.layoutControlItem9.TextSize = new System.Drawing.Size(79, 16);
            // 
            // layoutControlItem11
            // 
            this.layoutControlItem11.Control = this.ratingControl1;
            this.layoutControlItem11.ControlAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.layoutControlItem11.Location = new System.Drawing.Point(610, 0);
            this.layoutControlItem11.Name = "layoutControlItem11";
            this.layoutControlItem11.Size = new System.Drawing.Size(225, 34);
            this.layoutControlItem11.Text = "Povjerenje";
            this.layoutControlItem11.TextSize = new System.Drawing.Size(79, 13);
            // 
            // layoutControlItem7
            // 
            this.layoutControlItem7.Control = this.xtraTabControl1;
            this.layoutControlItem7.Location = new System.Drawing.Point(0, 413);
            this.layoutControlItem7.Name = "layoutControlItem7";
            this.layoutControlItem7.Size = new System.Drawing.Size(1113, 230);
            this.layoutControlItem7.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem7.TextVisible = false;
            // 
            // gridColumn1
            // 
            this.gridColumn1.Caption = "ID";
            this.gridColumn1.FieldName = "ID";
            this.gridColumn1.Name = "gridColumn1";
            // 
            // gridColumn2
            // 
            this.gridColumn2.Caption = "Datum";
            this.gridColumn2.FieldName = "Datum";
            this.gridColumn2.Name = "gridColumn2";
            this.gridColumn2.Visible = true;
            this.gridColumn2.VisibleIndex = 0;
            this.gridColumn2.Width = 79;
            // 
            // gridColumn3
            // 
            this.gridColumn3.Caption = "Broj";
            this.gridColumn3.FieldName = "Broj";
            this.gridColumn3.Name = "gridColumn3";
            this.gridColumn3.Visible = true;
            this.gridColumn3.VisibleIndex = 1;
            this.gridColumn3.Width = 45;
            // 
            // gridColumn4
            // 
            this.gridColumn4.Caption = "Reg. br.";
            this.gridColumn4.FieldName = "RegBr";
            this.gridColumn4.Name = "gridColumn4";
            this.gridColumn4.Visible = true;
            this.gridColumn4.VisibleIndex = 2;
            this.gridColumn4.Width = 87;
            // 
            // gridColumn5
            // 
            this.gridColumn5.Caption = "Marka";
            this.gridColumn5.FieldName = "Marka";
            this.gridColumn5.Name = "gridColumn5";
            this.gridColumn5.Visible = true;
            this.gridColumn5.VisibleIndex = 3;
            this.gridColumn5.Width = 125;
            // 
            // gridColumn6
            // 
            this.gridColumn6.Caption = "Boja";
            this.gridColumn6.FieldName = "Boja";
            this.gridColumn6.Name = "gridColumn6";
            this.gridColumn6.Visible = true;
            this.gridColumn6.VisibleIndex = 4;
            this.gridColumn6.Width = 108;
            // 
            // gridColumn7
            // 
            this.gridColumn7.Caption = "Brojilo start";
            this.gridColumn7.FieldName = "StanjeBrojilaStart";
            this.gridColumn7.Name = "gridColumn7";
            this.gridColumn7.Visible = true;
            this.gridColumn7.VisibleIndex = 5;
            this.gridColumn7.Width = 68;
            // 
            // gridColumn8
            // 
            this.gridColumn8.Caption = "Brojilo kraj";
            this.gridColumn8.FieldName = "StanjeBrojilaKraj";
            this.gridColumn8.Name = "gridColumn8";
            this.gridColumn8.Visible = true;
            this.gridColumn8.VisibleIndex = 6;
            this.gridColumn8.Width = 68;
            // 
            // gridColumn9
            // 
            this.gridColumn9.Caption = "Pređeni KM";
            this.gridColumn9.FieldName = "PredjeniKM";
            this.gridColumn9.Name = "gridColumn9";
            this.gridColumn9.Visible = true;
            this.gridColumn9.VisibleIndex = 7;
            this.gridColumn9.Width = 68;
            // 
            // gridColumn10
            // 
            this.gridColumn10.Caption = "Datum od";
            this.gridColumn10.FieldName = "DatumOd";
            this.gridColumn10.Name = "gridColumn10";
            this.gridColumn10.Visible = true;
            this.gridColumn10.VisibleIndex = 8;
            this.gridColumn10.Width = 68;
            // 
            // gridColumn12
            // 
            this.gridColumn12.Caption = "Razdužen";
            this.gridColumn12.FieldName = "IsRazduzen";
            this.gridColumn12.Name = "gridColumn12";
            this.gridColumn12.Visible = true;
            this.gridColumn12.VisibleIndex = 9;
            this.gridColumn12.Width = 57;
            // 
            // gridColumn11
            // 
            this.gridColumn11.Caption = "Dana";
            this.gridColumn11.FieldName = "DatumRazduzen";
            this.gridColumn11.Name = "gridColumn11";
            this.gridColumn11.Visible = true;
            this.gridColumn11.VisibleIndex = 10;
            this.gridColumn11.Width = 69;
            // 
            // gridColumn13
            // 
            this.gridColumn13.Caption = "Vraćen mjesto";
            this.gridColumn13.FieldName = "LokacijaVracenoNaziv";
            this.gridColumn13.Name = "gridColumn13";
            this.gridColumn13.Visible = true;
            this.gridColumn13.VisibleIndex = 11;
            this.gridColumn13.Width = 69;
            // 
            // gridColumn14
            // 
            this.gridColumn14.Caption = "Dana";
            this.gridColumn14.FieldName = "DanaZaRacun";
            this.gridColumn14.Name = "gridColumn14";
            this.gridColumn14.Visible = true;
            this.gridColumn14.VisibleIndex = 12;
            this.gridColumn14.Width = 69;
            // 
            // gridColumn15
            // 
            this.gridColumn15.Caption = "Cijena";
            this.gridColumn15.DisplayFormat.FormatString = "n2";
            this.gridColumn15.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.gridColumn15.FieldName = "Cijena";
            this.gridColumn15.Name = "gridColumn15";
            this.gridColumn15.Visible = true;
            this.gridColumn15.VisibleIndex = 13;
            this.gridColumn15.Width = 69;
            // 
            // gridColumn16
            // 
            this.gridColumn16.Caption = "Rabat";
            this.gridColumn16.DisplayFormat.FormatString = "P";
            this.gridColumn16.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.gridColumn16.FieldName = "Rabat";
            this.gridColumn16.Name = "gridColumn16";
            this.gridColumn16.Visible = true;
            this.gridColumn16.VisibleIndex = 14;
            this.gridColumn16.Width = 69;
            // 
            // gridColumn17
            // 
            this.gridColumn17.Caption = "PDV";
            this.gridColumn17.DisplayFormat.FormatString = "P";
            this.gridColumn17.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.gridColumn17.FieldName = "PDV";
            this.gridColumn17.Name = "gridColumn17";
            this.gridColumn17.Visible = true;
            this.gridColumn17.VisibleIndex = 15;
            this.gridColumn17.Width = 69;
            // 
            // gridColumn18
            // 
            this.gridColumn18.Caption = "Iznos";
            this.gridColumn18.DisplayFormat.FormatString = "n2";
            this.gridColumn18.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.gridColumn18.FieldName = "Iznos";
            this.gridColumn18.Name = "gridColumn18";
            this.gridColumn18.Visible = true;
            this.gridColumn18.VisibleIndex = 16;
            this.gridColumn18.Width = 109;
            // 
            // gridColumn19
            // 
            this.gridColumn19.Caption = "Plaćeno";
            this.gridColumn19.FieldName = "IsPlaceno";
            this.gridColumn19.Name = "gridColumn19";
            this.gridColumn19.Visible = true;
            this.gridColumn19.VisibleIndex = 17;
            this.gridColumn19.Width = 100;
            // 
            // gridColumn20
            // 
            this.gridColumn20.Caption = "Zadužen";
            this.gridColumn20.FieldName = "IsZaduzen";
            this.gridColumn20.Name = "gridColumn20";
            this.gridColumn20.Visible = true;
            this.gridColumn20.VisibleIndex = 9;
            this.gridColumn20.Width = 41;
            // 
            // frmKupacEdit
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoValidate = System.Windows.Forms.AutoValidate.EnableAllowFocusChange;
            this.ClientSize = new System.Drawing.Size(1133, 779);
            this.Controls.Add(this.dataLayoutControl1);
            this.Controls.Add(this.mainRibbonControl);
            this.Name = "frmKupacEdit";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Load += new System.EventHandler(this.ucOsoba_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dataLayoutControl1)).EndInit();
            this.dataLayoutControl1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ratingControl1.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.mainRibbonControl)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtBrVozacka.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtBrPasos.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtBrLK.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtEmail.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtMobilni.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtTelefon.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lkpMjestoStan.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtAdresa.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dtRodj.Properties.CalendarTimeProperties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dtRodj.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cbPol.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtID.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtJMBG.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.xtraTabControl1)).EndInit();
            this.xtraTabControl1.ResumeLayout(false);
            this.xtraTabPage1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.gridControl1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.memoNapomena.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureEdit1.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtPrezime.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtIme.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGeneratedGroup0)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForRoot)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForPhoto)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForFirstAndLastName)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForTabs)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForContact)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForBDateAndGender)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem13)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem12)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForHomeAddressAndPhone)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem18)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem19)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem22)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem17)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem20)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem10)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem9)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem11)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem7)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private DevExpress.XtraDataLayout.DataLayoutControl dataLayoutControl1;
        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup1;
        private DevExpress.XtraLayout.LayoutControlGroup autoGeneratedGroup0;
        private DevExpress.XtraLayout.LayoutControlGroup autoGroupForRoot;
        private DevExpress.XtraLayout.LayoutControlGroup autoGroupForPhoto;
        private DevExpress.XtraLayout.LayoutControlGroup autoGroupForFirstAndLastName;
        private DevExpress.XtraLayout.TabbedControlGroup autoGroupForTabs;
        private DevExpress.XtraLayout.LayoutControlGroup autoGroupForContact;
        private DevExpress.XtraLayout.LayoutControlGroup autoGroupForBDateAndGender;
        private DevExpress.XtraLayout.LayoutControlGroup autoGroupForHomeAddressAndPhone;
        private DevExpress.XtraTab.XtraTabControl xtraTabControl1;
        private DevExpress.XtraTab.XtraTabPage xtraTabPage1;
        private DevExpress.XtraEditors.MemoEdit memoNapomena;
        private DevExpress.XtraEditors.PictureEdit pictureEdit1;
        private DevExpress.XtraEditors.TextEdit txtPrezime;
        private DevExpress.XtraEditors.TextEdit txtIme;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem1;
        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup2;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem4;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem2;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem3;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem7;
        private DevExpress.XtraEditors.TextEdit txtJMBG;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem8;
        private DevExpress.XtraEditors.TextEdit txtID;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem9;
        private DevExpress.XtraEditors.DateEdit dtRodj;
        private DevExpress.XtraEditors.ComboBoxEdit cbPol;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem12;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem13;
        private DevExpress.XtraEditors.TextEdit txtEmail;
        private DevExpress.XtraEditors.TextEdit txtMobilni;
        private DevExpress.XtraEditors.TextEdit txtTelefon;
        private DevExpress.XtraEditors.LookUpEdit lkpMjestoStan;
        private DevExpress.XtraEditors.TextEdit txtAdresa;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem17;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem18;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem19;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem20;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem22;
        //private OsobaTabele.ucDjeca ucDjeca1;
        //private OsobaTabele.ucDjete ucDjete1;
        private DevExpress.XtraBars.Ribbon.RibbonControl mainRibbonControl;
        private DevExpress.XtraBars.BarButtonItem bbiSave;
        private DevExpress.XtraBars.BarButtonItem bbiSaveAndClose;
        private DevExpress.XtraBars.BarButtonItem bbiSaveAndNew;
        private DevExpress.XtraBars.BarButtonItem bbiReset;
        private DevExpress.XtraBars.BarButtonItem bbiDelete;
        private DevExpress.XtraBars.BarButtonItem bbiClose;
        private DevExpress.XtraBars.Ribbon.RibbonPage mainRibbonPage;
        private DevExpress.XtraBars.Ribbon.RibbonPageGroup mainRibbonPageGroup;
        private DevExpress.XtraEditors.TextEdit txtBrVozacka;
        private DevExpress.XtraEditors.TextEdit txtBrPasos;
        private DevExpress.XtraEditors.TextEdit txtBrLK;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem5;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem6;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem10;
        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup5;
        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup4;
        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup3;
        private DevExpress.XtraEditors.RatingControl ratingControl1;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem11;
        private DevExpress.XtraGrid.GridControl gridControl1;
        private DevExpress.XtraGrid.Views.Grid.GridView gridView1;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn1;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn2;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn3;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn4;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn5;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn6;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn7;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn8;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn9;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn10;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn12;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn11;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn13;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn14;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn15;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn16;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn17;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn18;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn19;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn20;
    }
}
