namespace CarRental.Forms
{
    partial class frmVoziloEdit

    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            DevExpress.Utils.ContextButton contextButton1 = new DevExpress.Utils.ContextButton();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmVoziloEdit));
            this.dataLayoutControl1 = new DevExpress.XtraDataLayout.DataLayoutControl();
            this.txtTipMotora = new DevExpress.XtraEditors.TextEdit();
            this.mainRibbonControl = new DevExpress.XtraBars.Ribbon.RibbonControl();
            this.bbiSave = new DevExpress.XtraBars.BarButtonItem();
            this.bbiSaveAndClose = new DevExpress.XtraBars.BarButtonItem();
            this.bbiSaveAndNew = new DevExpress.XtraBars.BarButtonItem();
            this.bbiReset = new DevExpress.XtraBars.BarButtonItem();
            this.bbiDelete = new DevExpress.XtraBars.BarButtonItem();
            this.bbiClose = new DevExpress.XtraBars.BarButtonItem();
            this.mainRibbonPage = new DevExpress.XtraBars.Ribbon.RibbonPage();
            this.mainRibbonPageGroup = new DevExpress.XtraBars.Ribbon.RibbonPageGroup();
            this.txtZapreminaMot = new DevExpress.XtraEditors.TextEdit();
            this.txtSnaga = new DevExpress.XtraEditors.TextEdit();
            this.txtBrojMotora = new DevExpress.XtraEditors.TextEdit();
            this.txtNosivost = new DevExpress.XtraEditors.TextEdit();
            this.txtNeto = new DevExpress.XtraEditors.TextEdit();
            this.txtCena = new DevExpress.XtraEditors.TextEdit();
            this.dtReg = new DevExpress.XtraEditors.DateEdit();
            this.txtGodina = new DevExpress.XtraEditors.TextEdit();
            this.txtTip = new DevExpress.XtraEditors.TextEdit();
            this.txtSasija = new DevExpress.XtraEditors.TextEdit();
            this.txtZapreminaRez = new DevExpress.XtraEditors.TextEdit();
            this.txtSjedista = new DevExpress.XtraEditors.TextEdit();
            this.txtVrata = new DevExpress.XtraEditors.TextEdit();
            this.txtID = new DevExpress.XtraEditors.TextEdit();
            this.xtraTabControl1 = new DevExpress.XtraTab.XtraTabControl();
            this.xtraTabPage1 = new DevExpress.XtraTab.XtraTabPage();
            this.gridControl1 = new DevExpress.XtraGrid.GridControl();
            this.gridView1 = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.memoNapomena = new DevExpress.XtraEditors.MemoEdit();
            this.pictureEdit1 = new DevExpress.XtraEditors.PictureEdit();
            this.txtRegBr = new DevExpress.XtraEditors.TextEdit();
            this.cbMarka = new DevExpress.XtraEditors.LookUpEdit();
            this.cbOblik = new DevExpress.XtraEditors.LookUpEdit();
            this.cbBoja = new DevExpress.XtraEditors.LookUpEdit();
            this.layoutControlGroup1 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.autoGeneratedGroup0 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.autoGroupForRoot = new DevExpress.XtraLayout.LayoutControlGroup();
            this.autoGroupForPhoto = new DevExpress.XtraLayout.LayoutControlGroup();
            this.layoutControlItem1 = new DevExpress.XtraLayout.LayoutControlItem();
            this.autoGroupForFirstAndLastName = new DevExpress.XtraLayout.LayoutControlGroup();
            this.autoGroupForTabs = new DevExpress.XtraLayout.TabbedControlGroup();
            this.autoGroupForContact = new DevExpress.XtraLayout.LayoutControlGroup();
            this.autoGroupForBDateAndGender = new DevExpress.XtraLayout.LayoutControlGroup();
            this.layoutControlGroup5 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.layoutControlItem12 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem3 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem8 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem11 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem13 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem14 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem15 = new DevExpress.XtraLayout.LayoutControlItem();
            this.autoGroupForHomeAddressAndPhone = new DevExpress.XtraLayout.LayoutControlGroup();
            this.layoutControlGroup4 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.layoutControlItem22 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem17 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem20 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem19 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem5 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem6 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem10 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem16 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem18 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem21 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlGroup2 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.layoutControlItem4 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem2 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem9 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem7 = new DevExpress.XtraLayout.LayoutControlItem();
            this.gridColumn1 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn2 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn3 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn4 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn5 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn6 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn7 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn8 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn9 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn10 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn11 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn12 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn13 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn14 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn15 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn16 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn17 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn18 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn19 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn20 = new DevExpress.XtraGrid.Columns.GridColumn();
            ((System.ComponentModel.ISupportInitialize)(this.dataLayoutControl1)).BeginInit();
            this.dataLayoutControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.txtTipMotora.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.mainRibbonControl)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtZapreminaMot.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtSnaga.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtBrojMotora.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtNosivost.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtNeto.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtCena.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dtReg.Properties.CalendarTimeProperties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dtReg.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtGodina.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtTip.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtSasija.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtZapreminaRez.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtSjedista.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtVrata.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtID.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.xtraTabControl1)).BeginInit();
            this.xtraTabControl1.SuspendLayout();
            this.xtraTabPage1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gridControl1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.memoNapomena.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureEdit1.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtRegBr.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cbMarka.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cbOblik.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cbBoja.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGeneratedGroup0)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForRoot)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForPhoto)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForFirstAndLastName)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForTabs)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForContact)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForBDateAndGender)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem12)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem11)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem13)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem14)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem15)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForHomeAddressAndPhone)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem22)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem17)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem20)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem19)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem10)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem16)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem18)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem21)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem9)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem7)).BeginInit();
            this.SuspendLayout();
            // 
            // dataLayoutControl1
            // 
            this.dataLayoutControl1.AllowCustomization = false;
            this.dataLayoutControl1.Controls.Add(this.txtTipMotora);
            this.dataLayoutControl1.Controls.Add(this.txtZapreminaMot);
            this.dataLayoutControl1.Controls.Add(this.txtSnaga);
            this.dataLayoutControl1.Controls.Add(this.txtBrojMotora);
            this.dataLayoutControl1.Controls.Add(this.txtNosivost);
            this.dataLayoutControl1.Controls.Add(this.txtNeto);
            this.dataLayoutControl1.Controls.Add(this.txtCena);
            this.dataLayoutControl1.Controls.Add(this.dtReg);
            this.dataLayoutControl1.Controls.Add(this.txtGodina);
            this.dataLayoutControl1.Controls.Add(this.txtTip);
            this.dataLayoutControl1.Controls.Add(this.txtSasija);
            this.dataLayoutControl1.Controls.Add(this.txtZapreminaRez);
            this.dataLayoutControl1.Controls.Add(this.txtSjedista);
            this.dataLayoutControl1.Controls.Add(this.txtVrata);
            this.dataLayoutControl1.Controls.Add(this.txtID);
            this.dataLayoutControl1.Controls.Add(this.xtraTabControl1);
            this.dataLayoutControl1.Controls.Add(this.memoNapomena);
            this.dataLayoutControl1.Controls.Add(this.pictureEdit1);
            this.dataLayoutControl1.Controls.Add(this.txtRegBr);
            this.dataLayoutControl1.Controls.Add(this.cbMarka);
            this.dataLayoutControl1.Controls.Add(this.cbOblik);
            this.dataLayoutControl1.Controls.Add(this.cbBoja);
            this.dataLayoutControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dataLayoutControl1.Location = new System.Drawing.Point(0, 116);
            this.dataLayoutControl1.Name = "dataLayoutControl1";
            this.dataLayoutControl1.OptionsCustomizationForm.DesignTimeCustomizationFormPositionAndSize = new System.Drawing.Rectangle(787, 321, 450, 400);
            this.dataLayoutControl1.Root = this.layoutControlGroup1;
            this.dataLayoutControl1.Size = new System.Drawing.Size(1133, 663);
            this.dataLayoutControl1.TabIndex = 0;
            // 
            // txtTipMotora
            // 
            this.txtTipMotora.Location = new System.Drawing.Point(481, 378);
            this.txtTipMotora.MenuManager = this.mainRibbonControl;
            this.txtTipMotora.Name = "txtTipMotora";
            this.txtTipMotora.Size = new System.Drawing.Size(616, 20);
            this.txtTipMotora.StyleController = this.dataLayoutControl1;
            this.txtTipMotora.TabIndex = 27;
            // 
            // mainRibbonControl
            // 
            this.mainRibbonControl.ExpandCollapseItem.Id = 0;
            this.mainRibbonControl.Items.AddRange(new DevExpress.XtraBars.BarItem[] {
            this.mainRibbonControl.ExpandCollapseItem,
            this.bbiSave,
            this.bbiSaveAndClose,
            this.bbiSaveAndNew,
            this.bbiReset,
            this.bbiDelete,
            this.bbiClose});
            this.mainRibbonControl.Location = new System.Drawing.Point(0, 0);
            this.mainRibbonControl.MaxItemId = 10;
            this.mainRibbonControl.MdiMergeStyle = DevExpress.XtraBars.Ribbon.RibbonMdiMergeStyle.Always;
            this.mainRibbonControl.Name = "mainRibbonControl";
            this.mainRibbonControl.Pages.AddRange(new DevExpress.XtraBars.Ribbon.RibbonPage[] {
            this.mainRibbonPage});
            this.mainRibbonControl.RibbonStyle = DevExpress.XtraBars.Ribbon.RibbonControlStyle.Office2013;
            this.mainRibbonControl.ShowApplicationButton = DevExpress.Utils.DefaultBoolean.False;
            this.mainRibbonControl.Size = new System.Drawing.Size(1133, 116);
            this.mainRibbonControl.ToolbarLocation = DevExpress.XtraBars.Ribbon.RibbonQuickAccessToolbarLocation.Hidden;
            // 
            // bbiSave
            // 
            this.bbiSave.Caption = "Snimi";
            this.bbiSave.Id = 2;
            this.bbiSave.ImageOptions.ImageUri.Uri = "Save";
            this.bbiSave.Name = "bbiSave";
            this.bbiSave.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.bbiSave_ItemClick);
            // 
            // bbiSaveAndClose
            // 
            this.bbiSaveAndClose.Caption = "Snimi i zatvori";
            this.bbiSaveAndClose.Id = 3;
            this.bbiSaveAndClose.ImageOptions.ImageUri.Uri = "SaveAndClose";
            this.bbiSaveAndClose.Name = "bbiSaveAndClose";
            this.bbiSaveAndClose.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.bbiSaveAndClose_ItemClick);
            // 
            // bbiSaveAndNew
            // 
            this.bbiSaveAndNew.Caption = "Snimi i novi";
            this.bbiSaveAndNew.Id = 4;
            this.bbiSaveAndNew.ImageOptions.ImageUri.Uri = "SaveAndNew";
            this.bbiSaveAndNew.Name = "bbiSaveAndNew";
            this.bbiSaveAndNew.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.bbiSaveAndNew_ItemClick);
            // 
            // bbiReset
            // 
            this.bbiReset.Caption = "Poništi izmjene";
            this.bbiReset.Id = 5;
            this.bbiReset.ImageOptions.ImageUri.Uri = "Reset";
            this.bbiReset.Name = "bbiReset";
            this.bbiReset.Visibility = DevExpress.XtraBars.BarItemVisibility.Never;
            // 
            // bbiDelete
            // 
            this.bbiDelete.Caption = "Ukloni sliku";
            this.bbiDelete.Id = 6;
            this.bbiDelete.ImageOptions.ImageUri.Uri = "Delete";
            this.bbiDelete.Name = "bbiDelete";
            this.bbiDelete.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.bbiDelete_ItemClick);
            // 
            // bbiClose
            // 
            this.bbiClose.Caption = "Zatvori";
            this.bbiClose.Id = 7;
            this.bbiClose.ImageOptions.ImageUri.Uri = "Close";
            this.bbiClose.Name = "bbiClose";
            this.bbiClose.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.bbiClose_ItemClick);
            // 
            // mainRibbonPage
            // 
            this.mainRibbonPage.Groups.AddRange(new DevExpress.XtraBars.Ribbon.RibbonPageGroup[] {
            this.mainRibbonPageGroup});
            this.mainRibbonPage.MergeOrder = 0;
            this.mainRibbonPage.Name = "mainRibbonPage";
            this.mainRibbonPage.Text = "Vozilo";
            // 
            // mainRibbonPageGroup
            // 
            this.mainRibbonPageGroup.AllowTextClipping = false;
            this.mainRibbonPageGroup.ItemLinks.Add(this.bbiSave);
            this.mainRibbonPageGroup.ItemLinks.Add(this.bbiSaveAndClose);
            this.mainRibbonPageGroup.ItemLinks.Add(this.bbiSaveAndNew);
            this.mainRibbonPageGroup.ItemLinks.Add(this.bbiReset);
            this.mainRibbonPageGroup.ItemLinks.Add(this.bbiDelete);
            this.mainRibbonPageGroup.ItemLinks.Add(this.bbiClose);
            this.mainRibbonPageGroup.Name = "mainRibbonPageGroup";
            this.mainRibbonPageGroup.ShowCaptionButton = false;
            this.mainRibbonPageGroup.Text = "Podaci";
            // 
            // txtZapreminaMot
            // 
            this.txtZapreminaMot.Location = new System.Drawing.Point(865, 354);
            this.txtZapreminaMot.MenuManager = this.mainRibbonControl;
            this.txtZapreminaMot.Name = "txtZapreminaMot";
            this.txtZapreminaMot.Properties.Mask.EditMask = "n0";
            this.txtZapreminaMot.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.Numeric;
            this.txtZapreminaMot.Size = new System.Drawing.Size(232, 20);
            this.txtZapreminaMot.StyleController = this.dataLayoutControl1;
            this.txtZapreminaMot.TabIndex = 26;
            // 
            // txtSnaga
            // 
            this.txtSnaga.Location = new System.Drawing.Point(481, 354);
            this.txtSnaga.MenuManager = this.mainRibbonControl;
            this.txtSnaga.Name = "txtSnaga";
            this.txtSnaga.Properties.Mask.EditMask = "n0";
            this.txtSnaga.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.Numeric;
            this.txtSnaga.Size = new System.Drawing.Size(290, 20);
            this.txtSnaga.StyleController = this.dataLayoutControl1;
            this.txtSnaga.TabIndex = 25;
            // 
            // txtBrojMotora
            // 
            this.txtBrojMotora.Location = new System.Drawing.Point(865, 330);
            this.txtBrojMotora.MenuManager = this.mainRibbonControl;
            this.txtBrojMotora.Name = "txtBrojMotora";
            this.txtBrojMotora.Size = new System.Drawing.Size(232, 20);
            this.txtBrojMotora.StyleController = this.dataLayoutControl1;
            this.txtBrojMotora.TabIndex = 24;
            // 
            // txtNosivost
            // 
            this.txtNosivost.Location = new System.Drawing.Point(993, 306);
            this.txtNosivost.MenuManager = this.mainRibbonControl;
            this.txtNosivost.Name = "txtNosivost";
            this.txtNosivost.Properties.Mask.EditMask = "n0";
            this.txtNosivost.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.Numeric;
            this.txtNosivost.Size = new System.Drawing.Size(104, 20);
            this.txtNosivost.StyleController = this.dataLayoutControl1;
            this.txtNosivost.TabIndex = 23;
            // 
            // txtNeto
            // 
            this.txtNeto.Location = new System.Drawing.Point(737, 306);
            this.txtNeto.MenuManager = this.mainRibbonControl;
            this.txtNeto.Name = "txtNeto";
            this.txtNeto.Properties.Mask.EditMask = "n0";
            this.txtNeto.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.Numeric;
            this.txtNeto.Size = new System.Drawing.Size(162, 20);
            this.txtNeto.StyleController = this.dataLayoutControl1;
            this.txtNeto.TabIndex = 22;
            // 
            // txtCena
            // 
            this.txtCena.Location = new System.Drawing.Point(481, 235);
            this.txtCena.MenuManager = this.mainRibbonControl;
            this.txtCena.Name = "txtCena";
            this.txtCena.Properties.Mask.EditMask = "n2";
            this.txtCena.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.Numeric;
            this.txtCena.Size = new System.Drawing.Size(616, 20);
            this.txtCena.StyleController = this.dataLayoutControl1;
            this.txtCena.TabIndex = 21;
            // 
            // dtReg
            // 
            this.dtReg.EditValue = null;
            this.dtReg.Location = new System.Drawing.Point(481, 211);
            this.dtReg.MenuManager = this.mainRibbonControl;
            this.dtReg.Name = "dtReg";
            this.dtReg.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.dtReg.Properties.CalendarTimeProperties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.dtReg.Size = new System.Drawing.Size(616, 20);
            this.dtReg.StyleController = this.dataLayoutControl1;
            this.dtReg.TabIndex = 20;
            // 
            // txtGodina
            // 
            this.txtGodina.Location = new System.Drawing.Point(481, 187);
            this.txtGodina.MenuManager = this.mainRibbonControl;
            this.txtGodina.Name = "txtGodina";
            this.txtGodina.Properties.Mask.EditMask = "n0";
            this.txtGodina.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.Numeric;
            this.txtGodina.Size = new System.Drawing.Size(616, 20);
            this.txtGodina.StyleController = this.dataLayoutControl1;
            this.txtGodina.TabIndex = 19;
            // 
            // txtTip
            // 
            this.txtTip.Location = new System.Drawing.Point(481, 115);
            this.txtTip.MenuManager = this.mainRibbonControl;
            this.txtTip.Name = "txtTip";
            this.txtTip.Size = new System.Drawing.Size(616, 20);
            this.txtTip.StyleController = this.dataLayoutControl1;
            this.txtTip.TabIndex = 16;
            // 
            // txtSasija
            // 
            this.txtSasija.Location = new System.Drawing.Point(481, 330);
            this.txtSasija.Name = "txtSasija";
            this.txtSasija.Size = new System.Drawing.Size(290, 20);
            this.txtSasija.StyleController = this.dataLayoutControl1;
            this.txtSasija.TabIndex = 11;
            // 
            // txtZapreminaRez
            // 
            this.txtZapreminaRez.Location = new System.Drawing.Point(481, 306);
            this.txtZapreminaRez.Name = "txtZapreminaRez";
            this.txtZapreminaRez.Properties.Mask.EditMask = "n0";
            this.txtZapreminaRez.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.Numeric;
            this.txtZapreminaRez.Size = new System.Drawing.Size(162, 20);
            this.txtZapreminaRez.StyleController = this.dataLayoutControl1;
            this.txtZapreminaRez.TabIndex = 10;
            // 
            // txtSjedista
            // 
            this.txtSjedista.Location = new System.Drawing.Point(865, 282);
            this.txtSjedista.Name = "txtSjedista";
            this.txtSjedista.Properties.Mask.EditMask = "n0";
            this.txtSjedista.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.Numeric;
            this.txtSjedista.Size = new System.Drawing.Size(232, 20);
            this.txtSjedista.StyleController = this.dataLayoutControl1;
            this.txtSjedista.TabIndex = 9;
            // 
            // txtVrata
            // 
            this.txtVrata.Location = new System.Drawing.Point(481, 282);
            this.txtVrata.Name = "txtVrata";
            this.txtVrata.Properties.Mask.EditMask = "n0";
            this.txtVrata.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.Numeric;
            this.txtVrata.Size = new System.Drawing.Size(290, 20);
            this.txtVrata.StyleController = this.dataLayoutControl1;
            this.txtVrata.TabIndex = 8;
            // 
            // txtID
            // 
            this.txtID.Location = new System.Drawing.Point(438, 12);
            this.txtID.Name = "txtID";
            this.txtID.Properties.Appearance.Font = new System.Drawing.Font("Tahoma", 14F);
            this.txtID.Properties.Appearance.Options.UseFont = true;
            this.txtID.Properties.ReadOnly = true;
            this.txtID.Size = new System.Drawing.Size(144, 30);
            this.txtID.StyleController = this.dataLayoutControl1;
            this.txtID.TabIndex = 3;
            // 
            // xtraTabControl1
            // 
            this.xtraTabControl1.Location = new System.Drawing.Point(12, 426);
            this.xtraTabControl1.Name = "xtraTabControl1";
            this.xtraTabControl1.SelectedTabPage = this.xtraTabPage1;
            this.xtraTabControl1.Size = new System.Drawing.Size(1109, 225);
            this.xtraTabControl1.TabIndex = 15;
            this.xtraTabControl1.TabPages.AddRange(new DevExpress.XtraTab.XtraTabPage[] {
            this.xtraTabPage1});
            // 
            // xtraTabPage1
            // 
            this.xtraTabPage1.Controls.Add(this.gridControl1);
            this.xtraTabPage1.Name = "xtraTabPage1";
            this.xtraTabPage1.Size = new System.Drawing.Size(1103, 197);
            this.xtraTabPage1.Text = "Kartica";
            // 
            // gridControl1
            // 
            this.gridControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridControl1.Location = new System.Drawing.Point(0, 0);
            this.gridControl1.MainView = this.gridView1;
            this.gridControl1.MenuManager = this.mainRibbonControl;
            this.gridControl1.Name = "gridControl1";
            this.gridControl1.Size = new System.Drawing.Size(1103, 197);
            this.gridControl1.TabIndex = 0;
            this.gridControl1.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] {
            this.gridView1});
            // 
            // gridView1
            // 
            this.gridView1.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] {
            this.gridColumn1,
            this.gridColumn2,
            this.gridColumn3,
            this.gridColumn4,
            this.gridColumn5,
            this.gridColumn6,
            this.gridColumn7,
            this.gridColumn8,
            this.gridColumn9,
            this.gridColumn10,
            this.gridColumn20,
            this.gridColumn12,
            this.gridColumn11,
            this.gridColumn13,
            this.gridColumn14,
            this.gridColumn15,
            this.gridColumn16,
            this.gridColumn17,
            this.gridColumn18,
            this.gridColumn19});
            this.gridView1.GridControl = this.gridControl1;
            this.gridView1.Name = "gridView1";
            this.gridView1.OptionsBehavior.Editable = false;
            this.gridView1.OptionsView.ShowGroupPanel = false;
            // 
            // memoNapomena
            // 
            this.memoNapomena.Location = new System.Drawing.Point(360, 80);
            this.memoNapomena.Name = "memoNapomena";
            this.memoNapomena.Size = new System.Drawing.Size(749, 330);
            this.memoNapomena.StyleController = this.dataLayoutControl1;
            this.memoNapomena.TabIndex = 7;
            // 
            // pictureEdit1
            // 
            this.pictureEdit1.Cursor = System.Windows.Forms.Cursors.Default;
            this.pictureEdit1.Location = new System.Drawing.Point(12, 12);
            this.pictureEdit1.Name = "pictureEdit1";
            contextButton1.Alignment = DevExpress.Utils.ContextItemAlignment.BottomFar;
            contextButton1.Caption = "Dodaj/promjeni fotografiju";
            contextButton1.Id = new System.Guid("8877d5fc-004a-4264-9174-58d9edcc153b");
            contextButton1.Name = "btnUcitajSliku";
            contextButton1.ToolTip = "Učitaj sliku";
            this.pictureEdit1.Properties.ContextButtons.Add(contextButton1);
            this.pictureEdit1.Properties.InitialImage = ((System.Drawing.Image)(resources.GetObject("pictureEdit1.Properties.InitialImage")));
            this.pictureEdit1.Properties.ShowCameraMenuItem = DevExpress.XtraEditors.Controls.CameraMenuItemVisibility.Auto;
            this.pictureEdit1.Properties.SizeMode = DevExpress.XtraEditors.Controls.PictureSizeMode.Squeeze;
            this.pictureEdit1.Properties.ZoomAccelerationFactor = 1D;
            this.pictureEdit1.Size = new System.Drawing.Size(332, 410);
            this.pictureEdit1.StyleController = this.dataLayoutControl1;
            this.pictureEdit1.TabIndex = 0;
            this.pictureEdit1.ContextButtonClick += new DevExpress.Utils.ContextItemClickEventHandler(this.pictureEdit1_ContextButtonClick);
            // 
            // txtRegBr
            // 
            this.txtRegBr.EditValue = "";
            this.txtRegBr.Location = new System.Drawing.Point(665, 12);
            this.txtRegBr.Name = "txtRegBr";
            this.txtRegBr.Properties.Appearance.Font = new System.Drawing.Font("Tahoma", 14F, System.Drawing.FontStyle.Bold);
            this.txtRegBr.Properties.Appearance.Options.UseFont = true;
            this.txtRegBr.Properties.Appearance.Options.UseTextOptions = true;
            this.txtRegBr.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.txtRegBr.Size = new System.Drawing.Size(456, 30);
            this.txtRegBr.StyleController = this.dataLayoutControl1;
            this.txtRegBr.TabIndex = 1;
            // 
            // cbMarka
            // 
            this.cbMarka.Location = new System.Drawing.Point(481, 91);
            this.cbMarka.Name = "cbMarka";
            this.cbMarka.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.cbMarka.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] {
            new DevExpress.XtraEditors.Controls.LookUpColumnInfo("ID", "ID"),
            new DevExpress.XtraEditors.Controls.LookUpColumnInfo("Naziv", 80, "Naziv")});
            this.cbMarka.Properties.DisplayMember = "Naziv";
            this.cbMarka.Properties.NullText = "";
            this.cbMarka.Properties.PopupSizeable = false;
            this.cbMarka.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.Standard;
            this.cbMarka.Properties.ValueMember = "ID";
            this.cbMarka.Size = new System.Drawing.Size(616, 20);
            this.cbMarka.StyleController = this.dataLayoutControl1;
            this.cbMarka.TabIndex = 5;
            // 
            // cbOblik
            // 
            this.cbOblik.Location = new System.Drawing.Point(481, 139);
            this.cbOblik.MenuManager = this.mainRibbonControl;
            this.cbOblik.Name = "cbOblik";
            this.cbOblik.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.cbOblik.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] {
            new DevExpress.XtraEditors.Controls.LookUpColumnInfo("ID", "ID"),
            new DevExpress.XtraEditors.Controls.LookUpColumnInfo("Naziv", 80, "Naziv")});
            this.cbOblik.Properties.DisplayMember = "Naziv";
            this.cbOblik.Properties.NullText = "";
            this.cbOblik.Properties.PopupSizeable = false;
            this.cbOblik.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.Standard;
            this.cbOblik.Properties.ValueMember = "ID";
            this.cbOblik.Size = new System.Drawing.Size(616, 20);
            this.cbOblik.StyleController = this.dataLayoutControl1;
            this.cbOblik.TabIndex = 17;
            // 
            // cbBoja
            // 
            this.cbBoja.Location = new System.Drawing.Point(481, 163);
            this.cbBoja.MenuManager = this.mainRibbonControl;
            this.cbBoja.Name = "cbBoja";
            this.cbBoja.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.cbBoja.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] {
            new DevExpress.XtraEditors.Controls.LookUpColumnInfo("ID", "ID"),
            new DevExpress.XtraEditors.Controls.LookUpColumnInfo("Naziv", 80, "Naziv")});
            this.cbBoja.Properties.DisplayMember = "Naziv";
            this.cbBoja.Properties.NullText = "";
            this.cbBoja.Properties.PopupSizeable = false;
            this.cbBoja.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.Standard;
            this.cbBoja.Properties.ValueMember = "ID";
            this.cbBoja.Size = new System.Drawing.Size(616, 20);
            this.cbBoja.StyleController = this.dataLayoutControl1;
            this.cbBoja.TabIndex = 18;
            // 
            // layoutControlGroup1
            // 
            this.layoutControlGroup1.CustomizationFormText = "Root";
            this.layoutControlGroup1.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            this.layoutControlGroup1.GroupBordersVisible = false;
            this.layoutControlGroup1.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.autoGeneratedGroup0});
            this.layoutControlGroup1.Location = new System.Drawing.Point(0, 0);
            this.layoutControlGroup1.Name = "Root";
            this.layoutControlGroup1.Size = new System.Drawing.Size(1133, 663);
            this.layoutControlGroup1.TextVisible = false;
            // 
            // autoGeneratedGroup0
            // 
            this.autoGeneratedGroup0.AllowDrawBackground = false;
            this.autoGeneratedGroup0.CustomizationFormText = "autoGeneratedGroup0";
            this.autoGeneratedGroup0.GroupBordersVisible = false;
            this.autoGeneratedGroup0.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.autoGroupForRoot});
            this.autoGeneratedGroup0.Location = new System.Drawing.Point(0, 0);
            this.autoGeneratedGroup0.Name = "autoGeneratedGroup0";
            this.autoGeneratedGroup0.Size = new System.Drawing.Size(1113, 643);
            // 
            // autoGroupForRoot
            // 
            this.autoGroupForRoot.CustomizationFormText = "Root";
            this.autoGroupForRoot.GroupBordersVisible = false;
            this.autoGroupForRoot.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.autoGroupForPhoto});
            this.autoGroupForRoot.Location = new System.Drawing.Point(0, 0);
            this.autoGroupForRoot.Name = "autoGroupForRoot";
            this.autoGroupForRoot.Size = new System.Drawing.Size(1113, 643);
            this.autoGroupForRoot.Text = "Root";
            // 
            // autoGroupForPhoto
            // 
            this.autoGroupForPhoto.CustomizationFormText = "Photo";
            this.autoGroupForPhoto.DefaultLayoutType = DevExpress.XtraLayout.Utils.LayoutType.Horizontal;
            this.autoGroupForPhoto.GroupBordersVisible = false;
            this.autoGroupForPhoto.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.layoutControlItem1,
            this.autoGroupForFirstAndLastName,
            this.layoutControlItem7});
            this.autoGroupForPhoto.Location = new System.Drawing.Point(0, 0);
            this.autoGroupForPhoto.Name = "autoGroupForPhoto";
            this.autoGroupForPhoto.Size = new System.Drawing.Size(1113, 643);
            this.autoGroupForPhoto.Text = "Photo";
            // 
            // layoutControlItem1
            // 
            this.layoutControlItem1.Control = this.pictureEdit1;
            this.layoutControlItem1.Location = new System.Drawing.Point(0, 0);
            this.layoutControlItem1.Name = "layoutControlItem1";
            this.layoutControlItem1.Size = new System.Drawing.Size(336, 414);
            this.layoutControlItem1.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem1.TextVisible = false;
            // 
            // autoGroupForFirstAndLastName
            // 
            this.autoGroupForFirstAndLastName.CustomizationFormText = "FirstAndLastName";
            this.autoGroupForFirstAndLastName.GroupBordersVisible = false;
            this.autoGroupForFirstAndLastName.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.autoGroupForTabs,
            this.layoutControlItem2,
            this.layoutControlItem9});
            this.autoGroupForFirstAndLastName.Location = new System.Drawing.Point(336, 0);
            this.autoGroupForFirstAndLastName.Name = "autoGroupForFirstAndLastName";
            this.autoGroupForFirstAndLastName.Size = new System.Drawing.Size(777, 414);
            this.autoGroupForFirstAndLastName.Text = "FirstAndLastName";
            // 
            // autoGroupForTabs
            // 
            this.autoGroupForTabs.CustomizationFormText = "Tabs";
            this.autoGroupForTabs.Location = new System.Drawing.Point(0, 34);
            this.autoGroupForTabs.Name = "autoGroupForTabs";
            this.autoGroupForTabs.SelectedTabPage = this.autoGroupForContact;
            this.autoGroupForTabs.SelectedTabPageIndex = 0;
            this.autoGroupForTabs.Size = new System.Drawing.Size(777, 380);
            this.autoGroupForTabs.TabPages.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.autoGroupForContact,
            this.layoutControlGroup2});
            this.autoGroupForTabs.Text = "Tabs";
            // 
            // autoGroupForContact
            // 
            this.autoGroupForContact.CustomizationFormText = "Podaci o vozilu";
            this.autoGroupForContact.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.autoGroupForBDateAndGender,
            this.autoGroupForHomeAddressAndPhone});
            this.autoGroupForContact.Location = new System.Drawing.Point(0, 0);
            this.autoGroupForContact.Name = "autoGroupForContact";
            this.autoGroupForContact.Size = new System.Drawing.Size(753, 334);
            this.autoGroupForContact.Text = "Podaci o vozilu";
            // 
            // autoGroupForBDateAndGender
            // 
            this.autoGroupForBDateAndGender.CustomizationFormText = "BDateAndGender";
            this.autoGroupForBDateAndGender.DefaultLayoutType = DevExpress.XtraLayout.Utils.LayoutType.Horizontal;
            this.autoGroupForBDateAndGender.GroupBordersVisible = false;
            this.autoGroupForBDateAndGender.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.layoutControlGroup5});
            this.autoGroupForBDateAndGender.Location = new System.Drawing.Point(0, 0);
            this.autoGroupForBDateAndGender.Name = "autoGroupForBDateAndGender";
            this.autoGroupForBDateAndGender.Size = new System.Drawing.Size(753, 191);
            this.autoGroupForBDateAndGender.Text = "BDateAndGender";
            // 
            // layoutControlGroup5
            // 
            this.layoutControlGroup5.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.layoutControlItem12,
            this.layoutControlItem3,
            this.layoutControlItem8,
            this.layoutControlItem11,
            this.layoutControlItem13,
            this.layoutControlItem14,
            this.layoutControlItem15});
            this.layoutControlGroup5.Location = new System.Drawing.Point(0, 0);
            this.layoutControlGroup5.Name = "layoutControlGroup5";
            this.layoutControlGroup5.Size = new System.Drawing.Size(753, 191);
            this.layoutControlGroup5.Text = "Opšti podaci";
            this.layoutControlGroup5.TextLocation = DevExpress.Utils.Locations.Left;
            // 
            // layoutControlItem12
            // 
            this.layoutControlItem12.Control = this.cbMarka;
            this.layoutControlItem12.Location = new System.Drawing.Point(0, 0);
            this.layoutControlItem12.Name = "layoutControlItem12";
            this.layoutControlItem12.Size = new System.Drawing.Size(710, 24);
            this.layoutControlItem12.Text = "Marka";
            this.layoutControlItem12.TextSize = new System.Drawing.Size(87, 13);
            // 
            // layoutControlItem3
            // 
            this.layoutControlItem3.Control = this.txtTip;
            this.layoutControlItem3.Location = new System.Drawing.Point(0, 24);
            this.layoutControlItem3.Name = "layoutControlItem3";
            this.layoutControlItem3.Size = new System.Drawing.Size(710, 24);
            this.layoutControlItem3.Text = "Tip";
            this.layoutControlItem3.TextSize = new System.Drawing.Size(87, 13);
            // 
            // layoutControlItem8
            // 
            this.layoutControlItem8.Control = this.cbOblik;
            this.layoutControlItem8.Location = new System.Drawing.Point(0, 48);
            this.layoutControlItem8.Name = "layoutControlItem8";
            this.layoutControlItem8.Size = new System.Drawing.Size(710, 24);
            this.layoutControlItem8.Text = "Oblik";
            this.layoutControlItem8.TextSize = new System.Drawing.Size(87, 13);
            // 
            // layoutControlItem11
            // 
            this.layoutControlItem11.Control = this.cbBoja;
            this.layoutControlItem11.Location = new System.Drawing.Point(0, 72);
            this.layoutControlItem11.Name = "layoutControlItem11";
            this.layoutControlItem11.Size = new System.Drawing.Size(710, 24);
            this.layoutControlItem11.Text = "Boja";
            this.layoutControlItem11.TextSize = new System.Drawing.Size(87, 13);
            // 
            // layoutControlItem13
            // 
            this.layoutControlItem13.Control = this.txtGodina;
            this.layoutControlItem13.Location = new System.Drawing.Point(0, 96);
            this.layoutControlItem13.Name = "layoutControlItem13";
            this.layoutControlItem13.Size = new System.Drawing.Size(710, 24);
            this.layoutControlItem13.Text = "Godište";
            this.layoutControlItem13.TextSize = new System.Drawing.Size(87, 13);
            // 
            // layoutControlItem14
            // 
            this.layoutControlItem14.Control = this.dtReg;
            this.layoutControlItem14.Location = new System.Drawing.Point(0, 120);
            this.layoutControlItem14.Name = "layoutControlItem14";
            this.layoutControlItem14.Size = new System.Drawing.Size(710, 24);
            this.layoutControlItem14.Text = "Datum registracije";
            this.layoutControlItem14.TextSize = new System.Drawing.Size(87, 13);
            // 
            // layoutControlItem15
            // 
            this.layoutControlItem15.Control = this.txtCena;
            this.layoutControlItem15.Location = new System.Drawing.Point(0, 144);
            this.layoutControlItem15.Name = "layoutControlItem15";
            this.layoutControlItem15.Size = new System.Drawing.Size(710, 24);
            this.layoutControlItem15.Text = "Cijena/dan (KM)";
            this.layoutControlItem15.TextSize = new System.Drawing.Size(87, 13);
            // 
            // autoGroupForHomeAddressAndPhone
            // 
            this.autoGroupForHomeAddressAndPhone.CustomizationFormText = "HomeAddressAndPhone";
            this.autoGroupForHomeAddressAndPhone.DefaultLayoutType = DevExpress.XtraLayout.Utils.LayoutType.Horizontal;
            this.autoGroupForHomeAddressAndPhone.GroupBordersVisible = false;
            this.autoGroupForHomeAddressAndPhone.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.layoutControlGroup4});
            this.autoGroupForHomeAddressAndPhone.Location = new System.Drawing.Point(0, 191);
            this.autoGroupForHomeAddressAndPhone.Name = "autoGroupForHomeAddressAndPhone";
            this.autoGroupForHomeAddressAndPhone.Size = new System.Drawing.Size(753, 143);
            this.autoGroupForHomeAddressAndPhone.Text = "HomeAddressAndPhone";
            // 
            // layoutControlGroup4
            // 
            this.layoutControlGroup4.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.layoutControlItem22,
            this.layoutControlItem17,
            this.layoutControlItem20,
            this.layoutControlItem19,
            this.layoutControlItem5,
            this.layoutControlItem6,
            this.layoutControlItem10,
            this.layoutControlItem16,
            this.layoutControlItem18,
            this.layoutControlItem21});
            this.layoutControlGroup4.Location = new System.Drawing.Point(0, 0);
            this.layoutControlGroup4.Name = "layoutControlGroup4";
            this.layoutControlGroup4.Size = new System.Drawing.Size(753, 143);
            this.layoutControlGroup4.Text = "Performanse";
            this.layoutControlGroup4.TextLocation = DevExpress.Utils.Locations.Left;
            // 
            // layoutControlItem22
            // 
            this.layoutControlItem22.Control = this.txtSasija;
            this.layoutControlItem22.Location = new System.Drawing.Point(0, 48);
            this.layoutControlItem22.Name = "layoutControlItem22";
            this.layoutControlItem22.Size = new System.Drawing.Size(384, 24);
            this.layoutControlItem22.Text = "Broj šasije";
            this.layoutControlItem22.TextSize = new System.Drawing.Size(87, 13);
            // 
            // layoutControlItem17
            // 
            this.layoutControlItem17.Control = this.txtVrata;
            this.layoutControlItem17.Location = new System.Drawing.Point(0, 0);
            this.layoutControlItem17.Name = "layoutControlItem17";
            this.layoutControlItem17.Size = new System.Drawing.Size(384, 24);
            this.layoutControlItem17.Text = "Vrata";
            this.layoutControlItem17.TextSize = new System.Drawing.Size(87, 13);
            // 
            // layoutControlItem20
            // 
            this.layoutControlItem20.Control = this.txtZapreminaRez;
            this.layoutControlItem20.Location = new System.Drawing.Point(0, 24);
            this.layoutControlItem20.Name = "layoutControlItem20";
            this.layoutControlItem20.Size = new System.Drawing.Size(256, 24);
            this.layoutControlItem20.Text = "Rezervoar (l)";
            this.layoutControlItem20.TextSize = new System.Drawing.Size(87, 13);
            // 
            // layoutControlItem19
            // 
            this.layoutControlItem19.Control = this.txtSjedista;
            this.layoutControlItem19.Location = new System.Drawing.Point(384, 0);
            this.layoutControlItem19.Name = "layoutControlItem19";
            this.layoutControlItem19.Size = new System.Drawing.Size(326, 24);
            this.layoutControlItem19.Text = "Sjedišta";
            this.layoutControlItem19.TextSize = new System.Drawing.Size(87, 13);
            // 
            // layoutControlItem5
            // 
            this.layoutControlItem5.Control = this.txtNeto;
            this.layoutControlItem5.Location = new System.Drawing.Point(256, 24);
            this.layoutControlItem5.Name = "layoutControlItem5";
            this.layoutControlItem5.Size = new System.Drawing.Size(256, 24);
            this.layoutControlItem5.Text = "Neto težina (kg)";
            this.layoutControlItem5.TextSize = new System.Drawing.Size(87, 13);
            // 
            // layoutControlItem6
            // 
            this.layoutControlItem6.Control = this.txtNosivost;
            this.layoutControlItem6.Location = new System.Drawing.Point(512, 24);
            this.layoutControlItem6.Name = "layoutControlItem6";
            this.layoutControlItem6.Size = new System.Drawing.Size(198, 24);
            this.layoutControlItem6.Text = "Nosivost (kg)";
            this.layoutControlItem6.TextSize = new System.Drawing.Size(87, 13);
            // 
            // layoutControlItem10
            // 
            this.layoutControlItem10.Control = this.txtBrojMotora;
            this.layoutControlItem10.Location = new System.Drawing.Point(384, 48);
            this.layoutControlItem10.Name = "layoutControlItem10";
            this.layoutControlItem10.Size = new System.Drawing.Size(326, 24);
            this.layoutControlItem10.Text = "Broj motora";
            this.layoutControlItem10.TextSize = new System.Drawing.Size(87, 13);
            // 
            // layoutControlItem16
            // 
            this.layoutControlItem16.Control = this.txtSnaga;
            this.layoutControlItem16.Location = new System.Drawing.Point(0, 72);
            this.layoutControlItem16.Name = "layoutControlItem16";
            this.layoutControlItem16.Size = new System.Drawing.Size(384, 24);
            this.layoutControlItem16.Text = "Snaga (kW)";
            this.layoutControlItem16.TextSize = new System.Drawing.Size(87, 13);
            // 
            // layoutControlItem18
            // 
            this.layoutControlItem18.Control = this.txtZapreminaMot;
            this.layoutControlItem18.Location = new System.Drawing.Point(384, 72);
            this.layoutControlItem18.Name = "layoutControlItem18";
            this.layoutControlItem18.Size = new System.Drawing.Size(326, 24);
            this.layoutControlItem18.Text = "Zapremina (cm3)";
            this.layoutControlItem18.TextSize = new System.Drawing.Size(87, 13);
            // 
            // layoutControlItem21
            // 
            this.layoutControlItem21.Control = this.txtTipMotora;
            this.layoutControlItem21.Location = new System.Drawing.Point(0, 96);
            this.layoutControlItem21.Name = "layoutControlItem21";
            this.layoutControlItem21.Size = new System.Drawing.Size(710, 24);
            this.layoutControlItem21.Text = "Tip motora";
            this.layoutControlItem21.TextSize = new System.Drawing.Size(87, 13);
            // 
            // layoutControlGroup2
            // 
            this.layoutControlGroup2.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.layoutControlItem4});
            this.layoutControlGroup2.Location = new System.Drawing.Point(0, 0);
            this.layoutControlGroup2.Name = "layoutControlGroup2";
            this.layoutControlGroup2.Size = new System.Drawing.Size(753, 334);
            this.layoutControlGroup2.Text = "Napomena";
            // 
            // layoutControlItem4
            // 
            this.layoutControlItem4.Control = this.memoNapomena;
            this.layoutControlItem4.Location = new System.Drawing.Point(0, 0);
            this.layoutControlItem4.Name = "layoutControlItem4";
            this.layoutControlItem4.Size = new System.Drawing.Size(753, 334);
            this.layoutControlItem4.Text = "Napomena";
            this.layoutControlItem4.TextLocation = DevExpress.Utils.Locations.Top;
            this.layoutControlItem4.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem4.TextVisible = false;
            // 
            // layoutControlItem2
            // 
            this.layoutControlItem2.Control = this.txtRegBr;
            this.layoutControlItem2.Location = new System.Drawing.Point(238, 0);
            this.layoutControlItem2.Name = "layoutControlItem2";
            this.layoutControlItem2.Size = new System.Drawing.Size(539, 34);
            this.layoutControlItem2.Text = "Registarski broj";
            this.layoutControlItem2.TextAlignMode = DevExpress.XtraLayout.TextAlignModeItem.AutoSize;
            this.layoutControlItem2.TextSize = new System.Drawing.Size(74, 13);
            this.layoutControlItem2.TextToControlDistance = 5;
            // 
            // layoutControlItem9
            // 
            this.layoutControlItem9.AppearanceItemCaption.Font = new System.Drawing.Font("Tahoma", 10F);
            this.layoutControlItem9.AppearanceItemCaption.Options.UseFont = true;
            this.layoutControlItem9.Control = this.txtID;
            this.layoutControlItem9.Location = new System.Drawing.Point(0, 0);
            this.layoutControlItem9.Name = "layoutControlItem9";
            this.layoutControlItem9.Size = new System.Drawing.Size(238, 34);
            this.layoutControlItem9.Text = "Šifra";
            this.layoutControlItem9.TextSize = new System.Drawing.Size(87, 16);
            // 
            // layoutControlItem7
            // 
            this.layoutControlItem7.Control = this.xtraTabControl1;
            this.layoutControlItem7.Location = new System.Drawing.Point(0, 414);
            this.layoutControlItem7.Name = "layoutControlItem7";
            this.layoutControlItem7.Size = new System.Drawing.Size(1113, 229);
            this.layoutControlItem7.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem7.TextVisible = false;
            // 
            // gridColumn1
            // 
            this.gridColumn1.Caption = "ID";
            this.gridColumn1.FieldName = "ID";
            this.gridColumn1.Name = "gridColumn1";
            // 
            // gridColumn2
            // 
            this.gridColumn2.Caption = "Datum";
            this.gridColumn2.FieldName = "Datum";
            this.gridColumn2.Name = "gridColumn2";
            this.gridColumn2.Visible = true;
            this.gridColumn2.VisibleIndex = 0;
            this.gridColumn2.Width = 88;
            // 
            // gridColumn3
            // 
            this.gridColumn3.Caption = "Broj";
            this.gridColumn3.FieldName = "Broj";
            this.gridColumn3.Name = "gridColumn3";
            this.gridColumn3.Visible = true;
            this.gridColumn3.VisibleIndex = 1;
            this.gridColumn3.Width = 45;
            // 
            // gridColumn4
            // 
            this.gridColumn4.Caption = "JMBG";
            this.gridColumn4.FieldName = "JMBG";
            this.gridColumn4.Name = "gridColumn4";
            this.gridColumn4.Visible = true;
            this.gridColumn4.VisibleIndex = 2;
            this.gridColumn4.Width = 52;
            // 
            // gridColumn5
            // 
            this.gridColumn5.Caption = "Prezime";
            this.gridColumn5.FieldName = "Prezime";
            this.gridColumn5.Name = "gridColumn5";
            this.gridColumn5.Visible = true;
            this.gridColumn5.VisibleIndex = 3;
            this.gridColumn5.Width = 128;
            // 
            // gridColumn6
            // 
            this.gridColumn6.Caption = "Ime";
            this.gridColumn6.FieldName = "Ime";
            this.gridColumn6.Name = "gridColumn6";
            this.gridColumn6.Visible = true;
            this.gridColumn6.VisibleIndex = 4;
            this.gridColumn6.Width = 111;
            // 
            // gridColumn7
            // 
            this.gridColumn7.Caption = "Brojilo start";
            this.gridColumn7.FieldName = "StanjeBrojilaStart";
            this.gridColumn7.Name = "gridColumn7";
            this.gridColumn7.Visible = true;
            this.gridColumn7.VisibleIndex = 5;
            this.gridColumn7.Width = 70;
            // 
            // gridColumn8
            // 
            this.gridColumn8.Caption = "Brojilo kraj";
            this.gridColumn8.FieldName = "StanjeBrojilaKraj";
            this.gridColumn8.Name = "gridColumn8";
            this.gridColumn8.Visible = true;
            this.gridColumn8.VisibleIndex = 6;
            this.gridColumn8.Width = 70;
            // 
            // gridColumn9
            // 
            this.gridColumn9.Caption = "Pređeni KM";
            this.gridColumn9.FieldName = "PredjeniKM";
            this.gridColumn9.Name = "gridColumn9";
            this.gridColumn9.Visible = true;
            this.gridColumn9.VisibleIndex = 7;
            this.gridColumn9.Width = 70;
            // 
            // gridColumn10
            // 
            this.gridColumn10.Caption = "Datum od";
            this.gridColumn10.FieldName = "DatumOd";
            this.gridColumn10.Name = "gridColumn10";
            this.gridColumn10.Visible = true;
            this.gridColumn10.VisibleIndex = 8;
            this.gridColumn10.Width = 70;
            // 
            // gridColumn11
            // 
            this.gridColumn11.Caption = "Dana";
            this.gridColumn11.FieldName = "DatumRazduzen";
            this.gridColumn11.Name = "gridColumn11";
            this.gridColumn11.Visible = true;
            this.gridColumn11.VisibleIndex = 10;
            this.gridColumn11.Width = 71;
            // 
            // gridColumn12
            // 
            this.gridColumn12.Caption = "Razdužen";
            this.gridColumn12.FieldName = "IsRazduzen";
            this.gridColumn12.Name = "gridColumn12";
            this.gridColumn12.Visible = true;
            this.gridColumn12.VisibleIndex = 9;
            this.gridColumn12.Width = 58;
            // 
            // gridColumn13
            // 
            this.gridColumn13.Caption = "Vraćen mjesto";
            this.gridColumn13.FieldName = "LokacijaVracenoNaziv";
            this.gridColumn13.Name = "gridColumn13";
            this.gridColumn13.Visible = true;
            this.gridColumn13.VisibleIndex = 11;
            this.gridColumn13.Width = 71;
            // 
            // gridColumn14
            // 
            this.gridColumn14.Caption = "Dana";
            this.gridColumn14.FieldName = "DanaZaRacun";
            this.gridColumn14.Name = "gridColumn14";
            this.gridColumn14.Visible = true;
            this.gridColumn14.VisibleIndex = 12;
            this.gridColumn14.Width = 71;
            // 
            // gridColumn15
            // 
            this.gridColumn15.Caption = "Cijena";
            this.gridColumn15.DisplayFormat.FormatString = "n2";
            this.gridColumn15.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.gridColumn15.FieldName = "Cijena";
            this.gridColumn15.Name = "gridColumn15";
            this.gridColumn15.Visible = true;
            this.gridColumn15.VisibleIndex = 13;
            this.gridColumn15.Width = 71;
            // 
            // gridColumn16
            // 
            this.gridColumn16.Caption = "Rabat";
            this.gridColumn16.DisplayFormat.FormatString = "P";
            this.gridColumn16.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.gridColumn16.FieldName = "Rabat";
            this.gridColumn16.Name = "gridColumn16";
            this.gridColumn16.Visible = true;
            this.gridColumn16.VisibleIndex = 14;
            this.gridColumn16.Width = 71;
            // 
            // gridColumn17
            // 
            this.gridColumn17.Caption = "PDV";
            this.gridColumn17.DisplayFormat.FormatString = "P";
            this.gridColumn17.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.gridColumn17.FieldName = "PDV";
            this.gridColumn17.Name = "gridColumn17";
            this.gridColumn17.Visible = true;
            this.gridColumn17.VisibleIndex = 15;
            this.gridColumn17.Width = 71;
            // 
            // gridColumn18
            // 
            this.gridColumn18.Caption = "Iznos";
            this.gridColumn18.DisplayFormat.FormatString = "n2";
            this.gridColumn18.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.gridColumn18.FieldName = "Iznos";
            this.gridColumn18.Name = "gridColumn18";
            this.gridColumn18.Visible = true;
            this.gridColumn18.VisibleIndex = 16;
            this.gridColumn18.Width = 112;
            // 
            // gridColumn19
            // 
            this.gridColumn19.Caption = "Plaćeno";
            this.gridColumn19.FieldName = "IsPlaceno";
            this.gridColumn19.Name = "gridColumn19";
            this.gridColumn19.Visible = true;
            this.gridColumn19.VisibleIndex = 17;
            this.gridColumn19.Width = 96;
            // 
            // gridColumn20
            // 
            this.gridColumn20.Caption = "Zadužen";
            this.gridColumn20.FieldName = "IsZaduzen";
            this.gridColumn20.Name = "gridColumn20";
            this.gridColumn20.Visible = true;
            this.gridColumn20.VisibleIndex = 9;
            this.gridColumn20.Width = 44;
            // 
            // frmVoziloEdit
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoValidate = System.Windows.Forms.AutoValidate.EnableAllowFocusChange;
            this.ClientSize = new System.Drawing.Size(1133, 779);
            this.Controls.Add(this.dataLayoutControl1);
            this.Controls.Add(this.mainRibbonControl);
            this.Name = "frmVoziloEdit";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Load += new System.EventHandler(this.frmVoziloEdit_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dataLayoutControl1)).EndInit();
            this.dataLayoutControl1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.txtTipMotora.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.mainRibbonControl)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtZapreminaMot.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtSnaga.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtBrojMotora.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtNosivost.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtNeto.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtCena.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dtReg.Properties.CalendarTimeProperties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dtReg.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtGodina.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtTip.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtSasija.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtZapreminaRez.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtSjedista.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtVrata.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtID.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.xtraTabControl1)).EndInit();
            this.xtraTabControl1.ResumeLayout(false);
            this.xtraTabPage1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.gridControl1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.memoNapomena.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureEdit1.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtRegBr.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cbMarka.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cbOblik.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cbBoja.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGeneratedGroup0)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForRoot)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForPhoto)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForFirstAndLastName)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForTabs)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForContact)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForBDateAndGender)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem12)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem11)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem13)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem14)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem15)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGroupForHomeAddressAndPhone)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem22)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem17)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem20)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem19)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem10)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem16)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem18)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem21)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem9)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem7)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private DevExpress.XtraDataLayout.DataLayoutControl dataLayoutControl1;
        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup1;
        private DevExpress.XtraLayout.LayoutControlGroup autoGeneratedGroup0;
        private DevExpress.XtraLayout.LayoutControlGroup autoGroupForRoot;
        private DevExpress.XtraLayout.LayoutControlGroup autoGroupForPhoto;
        private DevExpress.XtraLayout.LayoutControlGroup autoGroupForFirstAndLastName;
        private DevExpress.XtraLayout.TabbedControlGroup autoGroupForTabs;
        private DevExpress.XtraLayout.LayoutControlGroup autoGroupForContact;
        private DevExpress.XtraLayout.LayoutControlGroup autoGroupForBDateAndGender;
        private DevExpress.XtraLayout.LayoutControlGroup autoGroupForHomeAddressAndPhone;
        private DevExpress.XtraTab.XtraTabControl xtraTabControl1;
        private DevExpress.XtraTab.XtraTabPage xtraTabPage1;
        private DevExpress.XtraEditors.MemoEdit memoNapomena;
        private DevExpress.XtraEditors.PictureEdit pictureEdit1;
        private DevExpress.XtraEditors.TextEdit txtRegBr;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem1;
        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup2;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem4;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem2;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem7;
        private DevExpress.XtraEditors.TextEdit txtID;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem9;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem12;
        private DevExpress.XtraEditors.TextEdit txtSasija;
        private DevExpress.XtraEditors.TextEdit txtZapreminaRez;
        private DevExpress.XtraEditors.TextEdit txtSjedista;
        private DevExpress.XtraEditors.TextEdit txtVrata;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem17;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem19;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem20;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem22;
        //private OsobaTabele.ucDjeca ucDjeca1;
        //private OsobaTabele.ucDjete ucDjete1;
        private DevExpress.XtraBars.Ribbon.RibbonControl mainRibbonControl;
        private DevExpress.XtraBars.BarButtonItem bbiSave;
        private DevExpress.XtraBars.BarButtonItem bbiSaveAndClose;
        private DevExpress.XtraBars.BarButtonItem bbiSaveAndNew;
        private DevExpress.XtraBars.BarButtonItem bbiReset;
        private DevExpress.XtraBars.BarButtonItem bbiDelete;
        private DevExpress.XtraBars.BarButtonItem bbiClose;
        private DevExpress.XtraBars.Ribbon.RibbonPage mainRibbonPage;
        private DevExpress.XtraBars.Ribbon.RibbonPageGroup mainRibbonPageGroup;
        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup5;
        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup4;
        private DevExpress.XtraEditors.TextEdit txtCena;
        private DevExpress.XtraEditors.DateEdit dtReg;
        private DevExpress.XtraEditors.TextEdit txtGodina;
        private DevExpress.XtraEditors.TextEdit txtTip;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem3;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem8;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem11;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem13;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem14;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem15;
        private DevExpress.XtraEditors.TextEdit txtNosivost;
        private DevExpress.XtraEditors.TextEdit txtNeto;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem5;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem6;
        private DevExpress.XtraEditors.TextEdit txtBrojMotora;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem10;
        private DevExpress.XtraEditors.TextEdit txtTipMotora;
        private DevExpress.XtraEditors.TextEdit txtZapreminaMot;
        private DevExpress.XtraEditors.TextEdit txtSnaga;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem16;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem18;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem21;
        private DevExpress.XtraEditors.LookUpEdit cbMarka;
        private DevExpress.XtraEditors.LookUpEdit cbOblik;
        private DevExpress.XtraEditors.LookUpEdit cbBoja;
        private DevExpress.XtraGrid.GridControl gridControl1;
        private DevExpress.XtraGrid.Views.Grid.GridView gridView1;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn1;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn2;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn3;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn4;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn5;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn6;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn7;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn8;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn9;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn10;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn12;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn11;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn13;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn14;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn15;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn16;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn17;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn18;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn19;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn20;
    }
}
